### ISSUE TITLE
More contrast on title of article in elfeed

### ISSUE THREAD

**Issue by MBuchaus** [nashamri/spacemacs-theme#100]
I'm includeing a screen shot of the very faint title   This works well in monokai but spacemacs-dark is better for terminal and all around use .   

the Text I'm refering to in screenshot is  "[Collage Wifi] Network manager doesn't connect"  

If there is a settable var that I can tweak for this please let me know.

![elfeed color shot](https://user-images.githubusercontent.com/954897/34644852-4349d472-f304-11e7-8f2d-1eba9afa6fd3.png)

**Comment by nashamri** [comment]
Hey @MBuchaus, thanks for reporting this. Just pushed a commit to fix this.
Oh! this is issue number 100 :smile:
