### ISSUE TITLE
wrong keyword highlight in jsx/js-mode

### ISSUE THREAD

**Issue by it6** [nashamri/spacemacs-theme#101]
Is there any way to disable keywords highlighting when writing jsx inside js-mode(yes plain old js-mode). See the image below how `for` and `in` are highlighted in the text.

<img width="534" alt="jsx-keyword-highlight" src="https://user-images.githubusercontent.com/5510191/34966740-eda00e36-fa2b-11e7-81df-d07807c86985.png">

**Comment by nashamri** [comment]
Hello @it6,

This seems a bit outside the scope of spacemacs-theme. I did a quick check and this is what I got:
![screenshot_2018-01-16_16-12-07](https://user-images.githubusercontent.com/1207107/34990679-087f6a6a-fad8-11e7-92b1-14a476acaf0e.png)

I was using the `develop` branch of spacemacs. If you are not using spacemacs, you might want to take a look at the javascript layer and see what kind of configuration is there. http://develop.spacemacs.org/layers/+lang/javascript/README.html

**Comment by it6** [comment]
I am not using spacemacs(except for the theme), I see the javascript layer in spacemacs is using js2 mode which would fix this issue. I was wondering if a fix is possible for native js-mode not js2-mode.

**Comment by nashamri** [comment]
@it6 the clean and correct way to solve this, I think, is to change how the mode highlights the text. It might be possible to force the change by setting the keywords face to match the base face. But I'm not sure about how to approach this.

**Comment by nashamri** [comment]
@it6 I think this should be reported in the `js-mode` repo instead.

**Comment by it6** [comment]
I doubt there is a js-mode repo, it comes builtin with emacs.

**Comment by nashamri** [comment]
Yeah you are right :smile: well, the only thing I can think of is forcing the `font-lock-keyword-face` to have the same look as the base font. But that will remove any theming from all keywords. So, if you really want `js-mode` and you are not willing to use `js2-mode` or some other mode, I think there is no obvious solution for issue, other than a fix in `js-mode` of course.

**Comment by it6** [comment]
yes, honestly I am cool with the way it is, not a big deal thanks for your help.
