### ISSUE TITLE
typescript mode highlight not visible when expand region

### ISSUE THREAD

**Issue by it6** [nashamri/spacemacs-theme#102]
In typescript (tide) mode, I am not able to see distinction between current highlight and text highlighted using expand region. 

![spacemacs-expand-region](https://user-images.githubusercontent.com/5510191/34966897-431dc578-fa2d-11e7-83b7-aced2860f5fe.gif)

Below is the desired behavior.

![good-expand-region](https://user-images.githubusercontent.com/5510191/34966909-4ededdb6-fa2d-11e7-9091-1b231c38eb2b.gif)

**Comment by nashamri** [comment]
Hello @it6 thanks for reporting this :+1: 
What's the name of the theme that has the correct behaviour?

**Comment by it6** [comment]
Most of the built in themes, for example `adwaita` has the correct behavior.

**Comment by nashamri** [comment]
@it6 I think I need a bit more explanation here :smile:  How did you make the current selection?
As the gif below shows, it seems to be working when I highlight some text after searching for it and then expanding.
![01](https://user-images.githubusercontent.com/1207107/35001369-a59b7536-faf7-11e7-94fd-cc97ea6b7957.gif)

When I highlight some text say by the mouse or when I'm using evil mode (in VISUAL mode) this is the behavior I see using `adwaita` or `leuven`, for example:
 
![02](https://user-images.githubusercontent.com/1207107/35001740-7a6405c6-faf8-11e7-9a05-de13967227c3.gif)

**Comment by it6** [comment]
I use expand region https://github.com/magnars/expand-region.el to expand selection from the current point to the surrounding s-expression. That is when the highlight is invisible.

**Comment by nashamri** [comment]
Thanks @it6 :smile: yes I used magnar's region expand to grow the selection in the two gifs above. My question is about the "currently highlighted" text, before you expand the selection (the "espresso-popover-container" text). How did you highlight that text?

**Comment by it6** [comment]
I didn't have to do anything for that, it is already being highlighted by typescript (tide mode).

**Comment by nashamri** [comment]
Oh I see, so `tide-mode` is responsible for the highlighting, which means there's a face provided by the theme. I didn't support `tide-mode` yet, so let me have a look at it again.
The theme should work just fine independently from spacemacs :smile:

**Comment by nashamri** [comment]
I see there's a face called `tide-hl-identifier`, could this be the one?

**Comment by it6** [comment]
Yes, that is it. I disabled `tide-hl-identifier` now I see the expand region highlighting. Is there a way for `tide-hl-identifier` and `expand-region` to use different variations of highlight so they are both visible. 

Thanks for your help.

**Comment by nashamri** [comment]
Yeah I'm working on that right now, I'll push a fix for this soon.

**Comment by nashamri** [comment]
Okay so this is what I acheived so far.
When I highlight an identifier manually, this is the behavior now:
![03](https://user-images.githubusercontent.com/1207107/35065125-50f0db8e-fbdd-11e7-8e23-d3680b7a40be.gif)

When I enable the `tide-hl-identifier-mode` (which will highlight the identifier under the cursor), this is the behavior:
![04](https://user-images.githubusercontent.com/1207107/35065174-7de1be56-fbdd-11e7-8415-01105f179239.gif)

**Comment by it6** [comment]
looks awesome, thank you.

**Comment by nashamri** [comment]
All righty! it's all fixed now :smile: thanks @it6
