### ISSUE TITLE
Package disappeared from melpa?

### ISSUE THREAD

**Issue by ckruse** [nashamri/spacemacs-theme#103]
Hi there,

I did an package update this morning and it failed to update `spacemacs-theme`. It seems that this package disappeared from melpa, is that possible?

Best regards,

**Comment by ckruse** [comment]
Ok, this is probably because of https://twitter.com/melpa_emacs/status/956031413085724672 - sorry for the noise

**Comment by nashamri** [comment]
Good thing I was sleeping when this happened :smile: 
Thanks @ckruse
