### ISSUE TITLE
spacemacs-theme-comment-italic changes comment color

### ISSUE THREAD

**Issue by philiparvidsson** [nashamri/spacemacs-theme#104]
using the light theme, I love the green color of the comments. I also prefer italic comments, but setting `spacemacs-theme-comment-italic` to `t` changes the color of the comments. is this a bug?

**Comment by philiparvidsson** [comment]
any word on this?

**Comment by nashamri** [comment]
Hello @philiparvidsson sorry my late reply :smile: 
Yeah I guess this is a bug. Interestingly it doesn't happen with the dark variant of the theme.
I'm looking into it now.

**Comment by nashamri** [comment]
It's a feature!!
https://github.com/nashamri/spacemacs-theme/pull/83
lol I completely forgot about this. But I think the colors should be consistent across variants.

**Comment by philiparvidsson** [comment]
@nashamri what can I do to get the default color but with italicized text?

**Comment by nashamri** [comment]
yeah, you can add this in your `dotspacemacs/user-init`:

```elisp
  (custom-set-variables '(spacemacs-theme-custom-colors
                          '((comment-light . "#2aa1ae"))))

```

**Comment by philiparvidsson** [comment]
Thanks!
