### ISSUE TITLE
Faces for tool tips (flycheck-pos-tip, company-quickhelp, etc.)

### ISSUE THREAD

**Issue by bmag** [nashamri/spacemacs-theme#11]
The faces `popup-tip-face` and `tooltip` are not handled by spacemacs theme. These faces are used for some popups, such as company-quickhelp and flcyheck-pos-tip (and maybe more). I don't think that the default styles of these faces is bad, but maybe different styles would fit better in spacemacs theme.

company-quickhelp popup (face `tooltip`):
![2015-07-27-221742_666x608_scrot](https://cloud.githubusercontent.com/assets/4334375/8915575/86f549ac-34ae-11e5-97b3-8c5b2e83daa6.png)

flycheck-pos-tip popup (face `popup-tip-face`):
![2015-07-27-221506_666x608_scrot](https://cloud.githubusercontent.com/assets/4334375/8915576/8e0aff20-34ae-11e5-9c27-59f3a33b3745.png)

In my config I changed these faces to something similar to company's popup:
```elisp
;; `popup-tip-face' used by flycheck tips
`(popup-tip-face ((t (:foreground ,base :background ,active2 :bold nil))))
;; `tooltip' used by company-quickhelp tips
`(tooltip ((t (:foreground ,active1 :background "#ad9dca"))))
```

If you decide to change `popup-tip-face`, please note that it also inherits from the face of the text it hides. For example, you can see in the next image that the bold property was inherited from the hidden defconst (the text in the popup is normally not bold). This can be fixed by explicitly setting all face properties that we don't want to inherit (such as `:bold nil` to fix this example).
![2015-07-27-223737_666x608_scrot](https://cloud.githubusercontent.com/assets/4334375/8915858/25145d48-34b0-11e5-9a44-1e5d13cd516f.png)

**Comment by nashamri** [comment]
:+1: thanks @bmag  for reporting this. I'll work on it, hopefully tomorrow.

**Comment by nashamri** [comment]
`company-quickhelp` doesn't seem to be inheriting from `tooltip`. I've tested that on `develop` and `0.103.2` and I couldn't find that face.

**Comment by nashamri** [comment]
It seems that `company-quickhelp` is using this package `pos-tip` to create the popup. And if no face is set for that package, it falls back to the `tooltip` face.

More info here:
https://github.com/pitkali/pos-tip/blob/master/pos-tip.el#L542
https://github.com/pitkali/pos-tip/blob/master/pos-tip.el#L554

More investigation :smile:

**Comment by nashamri** [comment]
Yup! when I set `(setq pos-tip-background-color "#ff0000")` it does indeed change the background of the quickhelp tooltips.

**Comment by bmag** [comment]
Well, the current situation works for me, so thanks.
