### ISSUE TITLE
Italics for keywords

### ISSUE THREAD

**Issue by NerdsvilleCEO** [nashamri/spacemacs-theme#114]
Would it be feasible to add italics option for keywords to support fonts like [Dank mono](http://dank.sh)?

I was thinking I could build this out and go off of the changes here https://github.com/nashamri/spacemacs-theme/issues/82

**Comment by nashamri** [comment]
@NerdsvilleCEO Yeah of course, sorry I didn't have the time to work on the theme lately. Hopefully, soon I'll get enough time. I'm always open for PRs.

**Comment by nashamri** [comment]
@NerdsvilleCEO I just added a new them var `spacemacs-theme-keyword-italic` that toggles this. It's off by default. So make sure to toggle it on to try it out.

Thanks for this :smile: let me know if you see something wrong.

**Comment by NerdsvilleCEO** [comment]
Dang it lol I literally was going to do this today! Beat me to it, but I'm not going to complain :) trying it now!! :))

**Comment by nashamri** [comment]
lol better luck next time :smile:

**Comment by NerdsvilleCEO** [comment]
Hey @nashamri I am having trouble getting this to work in code buffers, seems to work in the messages buffer, but in a code file, keywords don't change to italics

**Comment by nashamri** [comment]
@NerdsvilleCEO Can you show me a screenshot, please?

**Comment by NerdsvilleCEO** [comment]
<img width="1680" alt="screen shot 2018-06-07 at 11 18 08 am" src="https://user-images.githubusercontent.com/5251847/41109231-7fe37624-6a44-11e8-9026-8c4afa6ab2ca.png">

**Comment by NerdsvilleCEO** [comment]
comment italics don't work for me either, but if I set font to italic face the chars show as italic

**Comment by NerdsvilleCEO** [comment]
<img width="693" alt="screen shot 2018-06-07 at 11 23 27 am" src="https://user-images.githubusercontent.com/5251847/41109531-38f04d36-6a45-11e8-9a62-830ac05c587d.png">

**Comment by NerdsvilleCEO** [comment]
<img width="1680" alt="screen shot 2018-06-07 at 11 27 32 am" src="https://user-images.githubusercontent.com/5251847/41109779-ce3cabf0-6a45-11e8-9d25-8249edc71066.png">

**Comment by NerdsvilleCEO** [comment]
I think there must be some mismatch between the variables and the value causing it to always default to false and choose normal slant, must be the naming or something

**Comment by NerdsvilleCEO** [comment]
<img width="873" alt="screen shot 2018-06-07 at 11 31 34 am" src="https://user-images.githubusercontent.com/5251847/41110004-5e1cb120-6a46-11e8-886b-e9c5ad22fc04.png">

**Comment by nashamri** [comment]
hmm it's working fine on my end. Recorded a little gif of that.
![italic-keywords](https://user-images.githubusercontent.com/1207107/41110176-70bce80a-6a81-11e8-8ba6-e0929656631f.gif)

**Comment by NerdsvilleCEO** [comment]
Looks like if I reload the theme it works, is there a way to reload automatically on startup so it registers the config?

**Comment by nashamri** [comment]
Yeah, just add `(setq spacemacs-theme-keyword-italic t)` to your `dotspacemacs/user-init` in your `.spacemacs`.

![screenshot_2018-06-07_18-40-50](https://user-images.githubusercontent.com/1207107/41110549-56dc5ea6-6a82-11e8-90d8-0712db117e19.png)

**Comment by NerdsvilleCEO** [comment]
Alright, thank you so much! 👍

**Comment by nashamri** [comment]
You are welcomed :smile: 

If you are using the `customize` interface to change options, just make sure you save the canges for future sessions. This video might be helpful:
https://www.youtube.com/watch?v=mMcc0IF1hV0

Cheers!
