### ISSUE TITLE
Add support for evil-goggles

### ISSUE THREAD

**Issue by syl20bnr** [nashamri/spacemacs-theme#115]
I just added `evil-goggles`, would be cool to have a better color for the flashing effect.
Seems not so trivial to add colors for it though: https://github.com/edkolev/evil-goggles/blob/master/evil-goggles.el#L260

**Comment by nashamri** [comment]
Sure thing

**Comment by syl20bnr** [comment]
I had the same behavior until I test with pulse disabled. Seems that pulsing cannot change the foreground color which makes it more annoying than useful. I disabled it by default in Spacemacs so we will have the full contrast with the correct foreground color.

Thank you for the quick addition! 💜

**Comment by nashamri** [comment]
Yeah you are right :smile: disabling pulse did solve the problem.
