### ISSUE TITLE
Cannot set comments or keywords to italic

### ISSUE THREAD

**Issue by williamJmelton** [nashamri/spacemacs-theme#116]
I see in the documentation that using M-x we can search for the var to change the comments and keywords to italic - however, when searching for these variables in the customize buffer the variables are not there. 

I thought maybe that spacemacs uses an old version of the theme without this capability so I replaced the theme files in my spacemacs-master/core/libs/spacemacs-theme folder with the files in this repo, but still no luck.

**Comment by nashamri** [comment]
Yeah the latest changes are there for the `develop` branch of spacemacs. However, if you replace the `spacemacs-common.el` file with the one in the folder `core/libs/spacemacs-theme` and restart spacemacs, I guess it should work.

**Comment by nashamri** [comment]
And in your `.spacemacs` add the vars you want in the `user-init` function:
![](https://user-images.githubusercontent.com/1207107/41110549-56dc5ea6-6a82-11e8-90d8-0712db117e19.png)

**Comment by williamJmelton** [comment]
Switched to development branch & everything is as expected. Thanks!
