### ISSUE TITLE
diff-hl colors are barely noticeable

### ISSUE THREAD

**Issue by valignatev** [nashamri/spacemacs-theme#118]
Hi! Thanks for this awesome theme!
Maybe it's just me, but diff-hl colors seem to be barely noticeable with the dark theme:
![image](https://user-images.githubusercontent.com/7038954/41551506-6a1288ce-736f-11e8-81e7-278544a0f7cf.png)
You can only see borders, but not the background. Light theme diff-hl colors are a bit brighter, but I have to really concentrate on them:
![image](https://user-images.githubusercontent.com/7038954/41551604-ac7fd95a-736f-11e8-90fb-16707d59b604.png)

My question is if this is an intended colors (e.g. not a bug).

Also, I've noticed this PR: https://github.com/nashamri/spacemacs-theme/pull/51, which made colors less bright.
I've checked how were they before this change:
![image](https://user-images.githubusercontent.com/7038954/41551763-31ac8fa6-7370-11e8-9503-ab19c4e854c9.png)
I agree, this is to much :) But maybe there could be some sane middle ground?
What do you think?

**Comment by nashamri** [comment]
@valignatev Hey, thanks for the kind words :purple_heart: . Yeah I agree, a middle ground solution would be the best thing to go for. There are already brighter variants of the background colors (ending with the `-s` suffix), so this should be easy. Fixing it now :smile:

**Comment by nashamri** [comment]
That should do it :smile:

**Comment by valignatev** [comment]
Wow, that was super fast! Looks perfect now, thanks a lot :heart:
