### ISSUE TITLE
Customization NOT automatically reloaded

### ISSUE THREAD

**Issue by ianpan870102** [nashamri/spacemacs-theme#123]
I really love this theme on my GNU Emacs, however I noticed whenever I restart Emacs, these two lines in my `custom-set-variables`:
```elisp
 '(spacemacs-theme-comment-bg nil)
 '(spacemacs-theme-comment-italic t)
```
would not be read and would require me to manually reload my `.emacs` file. After manual reloading the customization would then take place.
It doesn't bother me "that" much, after all it's just a few extra keystrokes, however it would be perfect if someone could fix this bug.

**Comment by nashamri** [comment]
Hey @ianpan870102 thanks for the kind words :smile: 
This might be related to this issue https://github.com/nashamri/spacemacs-theme/issues/122. I'll try to investigate this later today.

**Comment by nashamri** [comment]
@ianpan870102 I just tried this snippet below and it works fine. If you are using `use-package`, can you please try it in your config and let me know if it works with you or not?
```elisp
(use-package spacemacs-common
  :ensure spacemacs-theme
  :init (setq spacemacs-theme-comment-bg nil
	      spacemacs-theme-keyword-italic t)
  :config (load-theme 'spacemacs-dark t))
```

**Comment by ianpan870102** [comment]
You're welcome :) The syntax highlight support is hands-down the best I've come across. Keep me updated while you investigate the 'bug'!
p.s. I'm using the default package manager with the `require` keyword and I'm not planning to migrate to use-package yet (though I might in the future, I've heard good things about it).

**Comment by nashamri** [comment]
Hey @ianpan870102, can you check if this https://github.com/nashamri/spacemacs-theme/pull/144 fixes the issue?

**Comment by nashamri** [comment]
@ianpan870102 I just merged #144. Just wait a bit for MELPA to reflect the new update and you can easily test it.

**Comment by emelens** [comment]
My Package directory is in D drive.  '(package-user-dir "d:\\Users\\mlnsa\\.emacs.d\\elpa"))
I am not using spacemacs full set up. I have plain emacs and trying to install this theme
Everytime I restart emacs , I have to enable this again manually

**Comment by emelens** [comment]
I noticed that spacemacs-common.el was not getting compiled and there was no .elc file created.
I pasted all that file contents into spacemacs-dark-theme.el. 

This time, the theme got loaded fine.

**Comment by ianpan870102** [comment]
Hi @nashamri I must have missed your previous mentions...one year ago 😓
I've since migrated to using `use-package`, and this issue no longer exists.
Here's a sample config snippet I'm using right now:

```emacs-lisp
(use-package spacemacs-common
  :ensure spacemacs-theme
  :config
  (setq spacemacs-theme-comment-bg nil)
  (setq spacemacs-theme-comment-italic t)
  (setq spacemacs-theme-org-height nil)
  (load-theme 'spacemacs-light t))
```


@emelens I'm using vanilla emacs as well, if it helps, does my snippet above solve your issue? I'll close this issue for now but feel free to reopen a new one if you find something lacking.
