### ISSUE TITLE
structured-haskell-mode support

### ISSUE THREAD

**Issue by d12frosted** [nashamri/spacemacs-theme#13]
Hi, I really like this theme and would like to see out-of-box support of [structured-haskell-mode](https://github.com/chrisdone/structured-haskell-mode). Long story short - only two variables need to be configured:

* `shm-current-face`
* `shm-quarantine-face`

First one is like line highlight and second face is used to highlight errors.

I added following block in `custom-theme-set-faces`:

```
;;;;; structured-haskell-mode
     `(shm-current-face ((,class (:background ,bg2))))
     `(shm-quarantine-face ((,class (:background ,highlight))))
```

I don't think that `highlight` is the best option here, that's why I am asking for help. I tried to use `err` and `warn` but didn't like them very much.

**Comment by d12frosted** [comment]
Any update on this?

**Comment by nashamri** [comment]
Sorry for being late, I'll work on it soon.
I'm a little busy these days.

**Comment by d12frosted** [comment]
Oh, everything is fine. Take your time. :smile: 
Sorry for bothering!

**Comment by nashamri** [comment]
Many apologizes for the delay :smile:

**Comment by d12frosted** [comment]
Many thanks! This is great.

**Comment by d12frosted** [comment]
After some time using it I would like to thank you again. Colours are great!

**Comment by nashamri** [comment]
I'm glad you like it :)
