### ISSUE TITLE
org-mode: Large text-sizes repeating in dark-mode

### ISSUE THREAD

**Issue by Jonta** [nashamri/spacemacs-theme#131]
Reproduce: 

Put this into an org-file, in org-mode, with spacemacs-dark (current default) as theme:

```
* 1
** 2
*** 3
**** 4
***** 5
****** 6
******* 7
******** 8
********* 9
********** 10
```

Actual result: The largest text-size repeats from level 9

Desired result: Size shrinks from the start, but then stops at some point

Screenshot with numbers on different levels:

![screen shot 2018-12-24 at 13 57 16](https://user-images.githubusercontent.com/359397/50400395-a9f61680-0786-11e9-8b93-7ffd739c0115.png)

**Comment by nashamri** [comment]
Hmm, well org-mode defines 8 levels of `org-levels-{1-8}` https://code.orgmode.org/bzg/org-mode/src/master/lisp/org-faces.el#L48
After the 8th level, it cycles back to the settings of the first level. I'm not sure there's a way to fix this in the theme only.

As a workaround, that might work for you @Jonta, is to remove the varying sizes of org headers by setting this var to `nil`:
```elisp
(setq spacemacs-theme-org-height nil)
```

Hope this helps!

**Comment by nashamri** [comment]
As I was suspecting, this is an `org-mode` issue that should be reported upstream. Several well-known themes suffer from the same issue.
![screenshot_20190116_222113](https://user-images.githubusercontent.com/1207107/51273295-6be2c000-19dd-11e9-835e-e064d466e166.png)
![screenshot_20190116_222300](https://user-images.githubusercontent.com/1207107/51273305-70a77400-19dd-11e9-93b7-60e1328d6bbe.png)

Therefore, I'm going to close this issue.
