### ISSUE TITLE
Update readme mention of ediff "...-bg-s" colors

### ISSUE THREAD

**Issue by duianto** [nashamri/spacemacs-theme#133]
Since the ediff background colors were changed to not use the `...-bg-s` colors, the following paragraph in: https://github.com/nashamri/spacemacs-theme#override-themes-colors probably needs to be rewritten/removed.

>The green and red colors have two background versions. The green-bg and red-bg are normal light background colors. The green-bg-s, red-bg-s, and blue-bg-s are a stronger version and are used in ediff and places were text is added, deleted or changed.

**Comment by nashamri** [comment]
Fixed it :+1:
