### ISSUE TITLE
Solaire mode support

### ISSUE THREAD

**Issue by ema2159** [nashamri/spacemacs-theme#136]
It would be really cool if there was solaire mode support for this theme!

**Comment by nashamri** [comment]
You did it :smile: https://github.com/nashamri/spacemacs-theme/pull/146

**Comment by ema2159** [comment]
I did it quite some time ago but forgot to share it. A couple of days ago the theme got updated and it overwrited it so I redid it shared it so it doesn't happen again jaja 😅
