### ISSUE TITLE
Add support for evil-mc

### ISSUE THREAD

**Issue by duianto** [nashamri/spacemacs-theme#137]
With the `spacemacs-dark` theme, the characters on the `evil-mc` additional cursors are hard to see.

![evil-mc support](https://user-images.githubusercontent.com/13420573/54211320-62f40380-44e1-11e9-9fbb-3d1126296995.png)

#### Reproduction steps

- Start Spacemacs on the develop branch
(from at least Aug 2018 when the `multiple-cursors` layer was added)
- Open the scratch buffer
- Type:
```
test
test
test
test
test
```
- With the cursor on one of the words, press `grm` to create a cursor at the end of all instances.

#### Notes

Instead of using the same colors for the additional cursors as the active cursor, it would be better if the additional cursors had another color, to make the active cursor clearly visible.

Currently if the active and additional cursors are on space characters then there's no difference between the cursors.

![cursors on spaces](https://user-images.githubusercontent.com/13420573/54213804-5671aa00-44e5-11e9-9518-649ad420513a.png)

The active cursor can be moved between all `evil-mc` cursors by pressing `M-n` or `M-p`.

**Comment by nashamri** [comment]
All done. Thanks @duianto for your detailed issue report :purple_heart:

**Comment by duianto** [comment]
It might be better to use a non evil-state color for the fake cursors. Otherwise there might be a risk of confusion whether one is in normal or insert state.

Normal | Insert
-|-
![normal](https://user-images.githubusercontent.com/13420573/59263771-002a1980-8c42-11e9-8dba-a8533c6e54f7.png) | ![insert](https://user-images.githubusercontent.com/13420573/59263775-03250a00-8c42-11e9-8d6a-5ebe85b7afde.png)

These screenshots are probably to short, but if Emacs is maximized and the active cursor is at the top of the screen and a fake cursor is in the middle of the screen, then one might see the green cursor in the middle and think that one is in insert state and start typing.

**Comment by nashamri** [comment]
@duianto yeah I see what you are saying. Will update it.

**Comment by nashamri** [comment]
Done with https://github.com/nashamri/spacemacs-theme/commit/c5baa2f12a2e0b306f51977efa43699641b982eb

**Comment by duianto** [comment]
Normal | Insert
-|-
![normal](https://user-images.githubusercontent.com/13420573/59438662-37d8c300-8df4-11e9-85a4-06591f4d0cd9.png) | ![insert](https://user-images.githubusercontent.com/13420573/59438669-3b6c4a00-8df4-11e9-896c-a04b6b9733ea.png)
![normal-adjacent-cursors](https://user-images.githubusercontent.com/13420573/59438855-8be3a780-8df4-11e9-929c-cf7394ae1a0a.png) | ![insert-adjacent-cursors](https://user-images.githubusercontent.com/13420573/59438870-900fc500-8df4-11e9-82f5-476ca1ba4b43.png)

It's also easy to see the active cursor when they are on spaces:

![cursors-on-spaces](https://user-images.githubusercontent.com/13420573/59438934-a9b10c80-8df4-11e9-9517-dcb34049d74a.png)

Thanks 👍
