### ISSUE TITLE
Keys & Values are the same color in yaml mode

### ISSUE THREAD

**Issue by beardedprojamz** [nashamri/spacemacs-theme#14]
I think it's because variables look to be the same color as values. I don't know the best way to avoid this, but it'd make YAML files more readable.

<img width="129" alt="screen shot 2015-08-05 at 3 29 12 pm" src="https://cloud.githubusercontent.com/assets/877908/9097051/c185bc1c-3b86-11e5-82da-18b96ed6b16b.png">

Thanks for the Spacemacs theme!

**Comment by nashamri** [comment]
Many apologize for the delay. This issue is actually an issue with the *variables* face. `yaml-mode` uses the `font-lock-variable-name-face` for the keys in yaml files. So, this should make variable name standout a bit more in any mode.

Thanks for reporting this @beardedprojamz!

**Comment by beardedprojamz** [comment]
Thank you! :clap:
