### ISSUE TITLE
Improve color support for lsp-mode

### ISSUE THREAD

**Issue by rymndhng** [nashamri/spacemacs-theme#143]
The defaults set by the library are a bit hard on the eyes currently. Notice the yellow font in the top right:

Example:
![Screen Shot 2019-05-16 at 4 53 59 PM](https://user-images.githubusercontent.com/1694040/57894292-37e8a180-77fb-11e9-9ea9-ca5e94baa5a3.png)

**Comment by nashamri** [comment]
Hello @rymndhng it seems like this might be an `lsp-mode` issue. I might be mistaken as I don't use `lsp-mode`, but the only faces that this mode defines are:
```
lsp-face-highlight-read   
lsp-face-highlight-textual
lsp-face-highlight-write  
lsp-lens-face             
lsp-lens-mouse-face
```
And none of these faces are responsible for that yellow color. Can you please put your `point` (or cursor :smile: ) on that yellow text in the screenshot and invoke this command `M-x describe-char` and post the output?

**Comment by jordanwade90** [comment]
Most of the lsp-mode faces are defined in the lsp-ui package. That particular face is lsp-ui-sideline-code-action.
