### ISSUE TITLE
evil-ex-lazy-highlight isn't supported for a terminal

### ISSUE THREAD

**Issue by idanko** [nashamri/spacemacs-theme#145]
I run emacs with a doom configuration manager on my gnome-terminal with 256 color support. And when I use the asterisk key in the vi normal mode which is bind to `(evil-ex-search-word-forward &optional COUNT SYMBOL)` it doesn't highlight the selected symbol (I suppose it's the same for iTerm2). The `evil-ex-search-word-forward` in turn is under the `evil-ex-lazy-highlight` group which is currently missed in spacemacs-theme. It would be nice to have support for this face group.

![Screenshot from 2019-05-30 19-33-59](https://user-images.githubusercontent.com/8293386/58648220-ef100d00-8311-11e9-8e0c-6243f5b01f8e.png)

**Comment by nashamri** [comment]
@idanko it should be okay now :smile:
