### ISSUE TITLE
Strange Line wrapping using org-mode tags

### ISSUE THREAD

**Issue by Wheest** [nashamri/spacemacs-theme#148]
I am getting some strange line-wrapping when using org-mode headline tags and this theme.

You can see an example of what I mean here:

![Screenshot_20190708_203632](https://user-images.githubusercontent.com/16022573/60834283-a7a65780-a1c0-11e9-8025-a7e8f4865d8d.png)

With the raw org source being:
```
#+TAGS: reading(r) code(c)
#+STARTUP: overview

* Top Level Headline
** Level 2 headline
** Level 2 headline 2                                              :reading:
** Another                                                            :code:
** This one is fine

```

This occurs when multiple windows are open, but is fine when a single buffer is shown.

Am not sure if [this issue](https://github.com/nashamri/spacemacs-theme/pull/87#issue-140616731) is related.

**Comment by nashamri** [comment]
I just tried the above snippet, and I don't see the described behavior.
I'm going to close this. If this is still an issue, don't hesitate to comment :smile:
