### ISSUE TITLE
Cannot load spacemacs-theme with use-package

### ISSUE THREAD

**Issue by ema2159** [nashamri/spacemacs-theme#150]
I get this error:
`Error (use-package): Cannot load spacemacs-theme`

**Comment by tdd11235813** [comment]
you can try:
```lisp
(use-package spacemacs-common
  :ensure spacemacs-theme
;; ...
)

```

**Comment by ema2159** [comment]
Nice workaround. It also works with `(use-package spacemacs-dark/light ...`
