### ISSUE TITLE
Button text turns red on mouse click

### ISSUE THREAD

**Issue by duianto** [nashamri/spacemacs-theme#153]
Mouse clicking on the Spacemacs buffers `[Update Packages]` button, turns the text red.

![red color on mouse click spacemacs buffer button](https://user-images.githubusercontent.com/13420573/64149150-7abf9b00-ce25-11e9-834b-c26029bd6975.png)

The face seems to be: `widget-button-pressed`.

![widget faces](https://user-images.githubusercontent.com/13420573/64150215-10f4c080-ce28-11e9-9541-84fe0352c109.png)

The button works as expected, but the red color might be interpreted as an error.

![error faces](https://user-images.githubusercontent.com/13420573/64150251-2669ea80-ce28-11e9-8f44-d2907964e709.png)

Or as a warning, although most warning faces are orange, except for org-warning which is red.

![warning faces](https://user-images.githubusercontent.com/13420573/64150284-38e42400-ce28-11e9-8e3f-29b838f72dae.png)

**Comment by nashamri** [comment]
Thanks @duianto I just fixed this.

**Comment by duianto** [comment]
That's better than the red color. 👍

This is what it looks like with this fix:

![2020-03-23_12-52-33](https://user-images.githubusercontent.com/13420573/77315404-d12ff080-6d07-11ea-8902-08648f5d9138.png)
![2020-03-23_12-52-48](https://user-images.githubusercontent.com/13420573/77315414-d4c37780-6d07-11ea-835f-ab760c3f8bc4.png)

In the dark theme, the base text color is different from the color of the other buttons, so it's probably clear that something is going on with that button. But maybe it could be interpreted as if the button having been disabled since it has the same color as the normal text:
above (`[S P A C E M A C S]`) and below (`Recent files` and `Projects`) the buttons.

And in the light theme, the base color is quite close to the `[Release Notes]` and 
`[Search in Spacemacs]` text, so it's not clear that the button was just clicked.

Maybe it would be more clear which button was clicked, if it turned green?
```elisp
     `(widget-button-pressed ((,class (:foreground ,green))))
```
![2020-03-23_13-02-07](https://user-images.githubusercontent.com/13420573/77315569-0e947e00-6d08-11ea-8ae3-25d9e0bb48ac.png)
![2020-03-23_13-01-51](https://user-images.githubusercontent.com/13420573/77315576-0fc5ab00-6d08-11ea-9bac-166081a4e6c7.png)

**Comment by nashamri** [comment]
Yeah that makes sense, I'll update it now, thanks @duianto for your feedback :+1:

**Comment by nashamri** [comment]
Just amended the previous PR.
