### ISSUE TITLE
:extend keyword for Emacs 27

### ISSUE THREAD

**Issue by mnewt** [nashamri/spacemacs-theme#155]
As of a fairly recent Emacs 27.1, faces now require the :extend t property to extend to the end of the line. I'm currently doing this but there are probably others faces that need it set too:

```emacs-lisp
(set-face-attribute 'hl-line nil :extend t)
(set-face-attribute 'org-block-begin-line nil :extend t)
(set-face-attribute 'org-block nil :extend t)
(set-face-attribute 'org-block-end-line nil :extend t)
```

These properties should be added to the themes themselves though. Is there any reason not to go ahead and do this?

**Comment by nashamri** [comment]
Hello @madalu 

I just learned about this, and there is not reason not to implement it :smile: a PR would be appreciated if you want to tackle this.

It probably be as simple as changing https://github.com/nashamri/spacemacs-theme/blob/32ddc1a9b9f4f58ebe8410abc1124b7acf0f36b1/spacemacs-common.el#L195

To:
```elisp
`(hl-line ((,class (:background ,bg2 :extend t))))
```

The same goes for the other faces.

**Comment by mnewt** [comment]
@nashamri Great! I'll send a PR shortly

**Comment by nashamri** [comment]
We can close this now, thanks again @mnewt the PR has been merged.
