### ISSUE TITLE
Cannot open load file: No such file or directory, spacemacs-common

### ISSUE THREAD

**Issue by Shinyhero36** [nashamri/spacemacs-theme#164]
When I try to apply the dark the theme, I got the following error:
`
Cannot open load file: No such file or directory, spacemacs-common
`
and the theme doesn't load everytime I restart emacs(26.3).

**Comment by nashamri** [comment]
How did you apply it?

**Comment by Shinyhero36** [comment]
I try the following command on emacs `M-x package install RET spacemacs-theme` But it wasn't working.
So i downloaded the repo and put the .el files in the theme folder which is here:
`Emacs\share\emacs\26.3\etc\themes`.
I restarted emacs and go to `M-x customize-theme` ans selected the dark-theme.

**Comment by nashamri** [comment]
I did a quick screencast showing how to do that in a couple of ways from a vanilla emacs installation. There are many other, look for what suits you best.


[2020-04-04 18-36-38.zip](https://github.com/nashamri/spacemacs-theme/files/4431851/2020-04-04.18-36-38.zip)

**Comment by Shinyhero36** [comment]
after I edited the init.el file and restarted emacs. Packages don't install.
I am on windows by the way.

**Comment by nashamri** [comment]
I don't believe this is an issue with the theme. I would suggest you to look into how to install packages in general in emacs. Here are some popular package manager:
https://github.com/raxod502/straight.el
https://github.com/jwiegley/use-package
