### ISSUE TITLE
How to change title frame color?

### ISSUE THREAD

**Issue by it6** [nashamri/spacemacs-theme#165]
I currently use dark theme, the black text on the title frame is hardly visible.

can anyone help, what is that variable called?

Thanks.

![titlebar](https://user-images.githubusercontent.com/5510191/79687923-2f4ce680-8268-11ea-840e-ce633640473a.png)

**Comment by nashamri** [comment]
Hello there,
If this is the title shown in the window frame, then I don't think this is something you can do in the theme.

**Comment by it6** [comment]
Hi, yes this is the color on the window frame. 

Ohh ok, thanks. I will close this issue.

Do you happen to know outside of this theme how to change this color, really appreciate, thanks.

**Comment by nashamri** [comment]
I don't think this is possible from within Emacs, I think it's something that the window manager is responsible for, for your operating system.

**Comment by it6** [comment]
ohh ok, thanks a lot.
