### ISSUE TITLE
Add support for highlight-thing

### ISSUE THREAD

**Issue by ianpan870102** [nashamri/spacemacs-theme#166]
**Highlight-thing** is a package that provides almost identical functionalities to **highlight-symbol**. IMO it's a good idea to add support for the former and style it exactly like the latter.

**Comment by nashamri** [comment]
I think someone fixed this :roll_eyes: :smile:

**Comment by ianpan870102** [comment]
> I think someone fixed this

Haha yup I wonder who it was! Anyways thanks for merging hahaha
