### ISSUE TITLE
[Readability] diff-hl difficult to read

### ISSUE THREAD

**Issue by ianpan870102** [nashamri/spacemacs-theme#168]
Hi @nashamri thanks for this great theme (again)!

I have noticed that **diff-hl (git gutter)** is kind of difficult to read. From my experience, many other Emacs themes and modern editors actually make the background of the gutter quite noticeable.

### Current Spacemacs theme appearance

Note the faded green and blue gutters on the left fringe (indicating addition and modification)

![image](https://user-images.githubusercontent.com/36686900/83605674-e4cec180-a5aa-11ea-8f83-fc9271457d3f.png)

### Example reference I: Sublime Text (a popular editor)

The same kind of git gutter style can also be found in Microsoft's Visual Studio and Visual Studio Code.

![image](https://user-images.githubusercontent.com/36686900/83606217-cf0dcc00-a5ab-11ea-8f90-f75e334d63e6.png)

## Example reference II: Emacs' doom-themes (a popular theme pack, maintained together with Doom Emacs)

![image](https://user-images.githubusercontent.com/36686900/83606499-4d6a6e00-a5ac-11ea-86f0-ed2fd217e533.png)

# My proposal for Spacemacs theme

### Light

![image](https://user-images.githubusercontent.com/36686900/83605807-25c6d600-a5ab-11ea-9643-2ef2b2ff1b9b.png)

### Dark 

![image](https://user-images.githubusercontent.com/36686900/83606591-725ee100-a5ac-11ea-872a-5e3736013432.png)

## Pull Request

If you agree to the change, I will submit a pull request to improve this issue.

**Comment by nashamri** [comment]
@ianpan870102 heeey there :smile: 
This looks great to me and yeah a PR is so welcomed!
Thanks for this and I'm so sorry for being late to check it out (life is a bit crazy here :smile:)

**Comment by ianpan870102** [comment]
Hi @nashamri I just created a Pull Request https://github.com/nashamri/spacemacs-theme/pull/169

> Thanks for this and I'm so sorry for being late to check it out (life is a bit crazy here 😄)

No problem at all! Hope you're doing well :) Glad to contribute
