### ISSUE TITLE
Please make org agenda headings respect `spacemacs-theme-org-height`

### ISSUE THREAD

**Issue by swaroopch** [nashamri/spacemacs-theme#17]
The Org Agenda looks misaligned in the otherwise-beautiful Spacemacs theme, can you please make the `org-agenda-date*`, etc. respect the `spacemacs-theme-org-height` flag, which would make org agenda usable with the spacemacs theme. Thanks!

**Comment by nashamri** [comment]
Thanks @swaroopch, I've fixed this. Although, I'm thinking of making all org-agenda headings fixed in size. The varying headings heights of the agenda view might be a bit distracting. What do you think?

**Comment by nashamri** [comment]
It probably will take couple of hours for MELPA to reflect the changes.
