### ISSUE TITLE
Modeline theme

### ISSUE THREAD

**Issue by xaransh** [nashamri/spacemacs-theme#176]
How are you getting the modeline look as in the previews? I am not getting the same after using the loading the theme.

**Comment by nashamri** [comment]
You can customize this variable `powerline-default-separator` to get different separators. The possible values are:
nil, alternate, arrow, arrow-fade, bar, box, brace, butt, chamfer, contour, curve, rounded, roundstub, wave, zigzag, slant, utf-8.

If you are using spacemacs, just add this to your `dotspacemacs/user-config`:
```elisp
  (setq powerline-default-separator 'zigzag)
```
