### ISSUE TITLE
Light theme hs poor visibility for branch names in magit

### ISSUE THREAD

**Issue by rymndhng** [nashamri/spacemacs-theme#18]
Light theme doens't have good visibility of branch names compared to the dark theme. See:

![screen shot 2015-08-13 at 11 15 27](https://cloud.githubusercontent.com/assets/1694040/9257863/fef73126-41ac-11e5-8e63-e663e15e71e9.png)

![screen shot 2015-08-13 at 11 15 41](https://cloud.githubusercontent.com/assets/1694040/9257873/0c6de0fc-41ad-11e5-948a-7a36a8d2125e.png)

**Comment by nashamri** [comment]
Yes, the light version has lower contrast compared to the dark one. Working on it.

**Comment by nashamri** [comment]
Just a quick question, are you on `develop` or on the stable `0.130`?

**Comment by rymndhng** [comment]
I use the one on MELPA, so that should be master? I made the screenshots after pulling the latest (3 hrs ago).

**Comment by nashamri** [comment]
Oh okay. I actually meant for spacemacs starter kit not spacemacs-theme. I thought you were using spacemacs because the develop version uses magit 2.1 and they changed some faces in 2.2 :smile: no worries, i'll fix this now.

**Comment by nashamri** [comment]
Wait for MELPA to reflect the changes and tell me what you think :smile:

**Comment by rymndhng** [comment]
Thanks, it much better now. Cheers
