### ISSUE TITLE
highlighting of the zsh prompt in *shell*

### ISSUE THREAD

**Issue by ForrestHilton** [nashamri/spacemacs-theme#184]
highlighting of the zsh prompt in *shell*

The prompt in the shell buffer is not legible due to the highlighting.
![Screenshot from 2021-05-26 23-49-43](https://user-images.githubusercontent.com/52688444/119767879-57504580-be7d-11eb-9724-465e89afafde.png)
The way its done in ansi-term is fine, though the most correct is the way its done on right monitor.

**Comment by nashamri** [comment]
@ForrestHilton hey there, I'm not sure what face `shell` uses for highlighting? If you are using spacemacs, can you click on the highlighted line and run `SPC h d c` to see the properties of the face.

**Comment by ForrestHilton** [comment]
Issue was fixed. Probably by you.
