### ISSUE TITLE
Strange behavior on org-bullets in Doom emacs

### ISSUE THREAD

**Issue by quarkquartet** [nashamri/spacemacs-theme#185]
I installed this theme. But in org-mode, the bullet behave like this. The starts appears on the side.
<img width="762" alt="image" src="https://user-images.githubusercontent.com/26316540/120380104-bb945e80-c2ee-11eb-8005-91b05302b191.png">
My emacs is Doom Emacs. 
Why this behaviour?

**Comment by nashamri** [comment]
@quarkquartet try this `(setq org-hide-leading-stars t)`
