### ISSUE TITLE
auto-highlight-symbol, new default face, hard to see cursor

### ISSUE THREAD

**Issue by duianto** [nashamri/spacemacs-theme#186]
The `auto-highlight-symbol` package has added a new face:
`ahs-plugin-default-face`
https://github.com/jcs-elpa/auto-highlight-symbol/blob/93458049093e902045fde2439bd1aed16d3e631d/auto-highlight-symbol.el#L445

It uses the color: "Orange1" as the background.

This is very close evil normal state cursors color,
which seems to use the face: `spacemacs-normal-face`
`       Background: DarkGoldenrod2`

![emacs_l18w2yvvMe](https://user-images.githubusercontent.com/13420573/124361671-7f775500-dc30-11eb-98cf-53314edad0e5.png)

This can make it difficult to find the normal state cursor,
at least if it's a long symbol.

**Comment by lebensterben** [comment]
Orange seems to be a very intuitive choice for highlighting.

Maybe we should change evil-normal-state cursor color instead.
