### ISSUE TITLE
Org mode `org-headline-done` face

### ISSUE THREAD

**Issue by dschrempf** [nashamri/spacemacs-theme#188]
Newer versions of Org mode change the default face for DONE headlines. The Spacemacs theme should probably provide a sane default face in this case. See also https://github.com/syl20bnr/spacemacs/issues/15055

**Comment by nashamri** [comment]
Hello @dschrempf thanks for reporting this. I've added two new faces for org todo headlines, and I've turned the `org-fontify-done-headline` off by default.

**Comment by dschrempf** [comment]
Thank you very much!
