### ISSUE TITLE
Face for highlight-indentation-mode is invisible

### ISSUE THREAD

**Issue by bmag** [nashamri/spacemacs-theme#19]
highlight-indentation-mode is supposed to show the indentation level of each line by giving a different background to some of the whitespaces in the beginning of each line.
In spacemacs-theme, these visual clues are invisible. That's because `highlight-indentation-face` inherits from the fringe's face, but in spacemacs-theme that's the same face as the regular background. Hence, the "highlighted" blocks have the same color as the background.

**Comment by nashamri** [comment]
Thanks @bmag :+1:
