### ISSUE TITLE
`ansi-color-names-vector` is obsolete

### ISSUE THREAD

**Issue by mcfarljm** [nashamri/spacemacs-theme#194]
It appears that with Emacs 28.1 `ansi-color-names-vector` is obsolete. From the help:
```
This variable is obsolete.  To customize the display of colors used by
ansi-color, change ’ansi-color-COLOR’, e.g. ‘ansi-color-red’.  To
customize the actual faces used (e.g. to temporarily display SGR
control sequences differently), use ‘ansi-color-normal-colors-vector’.
```
This means that certain colored terminal output (e.g., from `shell`) doesn't get colored according to the colors specified by the spacemacs theme, making it difficult to read.  See also #50.

Judging from the help, it looks like the solution would be for the theme to set the values of `ansi-color-red`, etc.

**Comment by nashamri** [comment]
@mcfarljm Thanks for reporting this. I think it's fixed now. Also, I've pushed a new tag (0.3) for the theme.
