### ISSUE TITLE
Python highlighting

### ISSUE THREAD

**Issue by fladd** [nashamri/spacemacs-theme#20]
The theme is suboptimal for Python highlighting.

Please see https://github.com/syl20bnr/spacemacs/issues/3195 for more details and screenshots.

**Comment by fladd** [comment]
I am also curious to learn why the official screenshot of the new Spacemacs release, shows Python highlighting with completely different colours?
https://raw.githubusercontent.com/syl20bnr/spacemacs/master/doc/img/spacemacs-python.png

**Comment by robbyoconnor** [comment]
Because of [this](https://github.com/syl20bnr/spacemacs/tree/develop/layers/colors). Specifically [rainbow-identifers](https://github.com/Fanael/rainbow-identifiers). I linked to `develop` but the same codebase is found in `master`. 

I figured i would post here as well.

**Comment by fladd** [comment]
Yes, thanks.

The original issue with the default colours still persists, though.

**Comment by nashamri** [comment]
Thanks @fladd @robbyoconnor yeah I was wondering why the screenshot looks like that.
I'll fix this issue with python highlighting soon :smile:

**Comment by nashamri** [comment]
@fladd hope you like the new changes :smile: it will take a bit for MELPA to see the changes.

**Comment by fladd** [comment]
@nashamri It is a bit better, however, there are still two things:

1) Comments and strings look almost identical (I don't know if this is by intention, but it feels weird)

2) Line numbers are now much too dark (I can barely see them against the black background).

**Comment by nashamri** [comment]
@fladd yeah I guess you are right about the line numbers. I've made them a bit more visible now.
For the comments vs string colors, the idea was to have the comments more blue-ish and the strings more green. I've tweaked them too so let me know what you think of the new change now.

**Comment by fladd** [comment]
@nashamri Yes, it is definitely getting better! The colour composition still feels a bit restless to me, though. Cannot really say why, unfortunately.

**Comment by nashamri** [comment]
@fladd Is that only in the dark variant or even for the light variant too?

**Comment by fladd** [comment]
@nashamri To be honest, it is a bit worse on the light one. It lacks contrast somehow. As if the colours do not really come through, in comparison to the backgrounds while/beige.

**Comment by nashamri** [comment]
@fladd hehehe okay I might give it another try. Thanks for the feedback :+1:

**Comment by fladd** [comment]
@nashamri Sure, glad to help...hope this does help...I like the idea of a dedicated Spacemacs theme for this amazing editor :-)

**Comment by fladd** [comment]
@nashamri I just realized that the comments in the light version are still green. Shouldn't all colours be consistent between the two versions of the theme? Or isn't that the idea?

**Comment by nashamri** [comment]
@fladd Actually the two variants have two sets of color schemes. It's not just the background that changes. Hmmm, I'm pretty sure the strings and comments are different but it might be less apparent in the light version.

There's an option that might help with comment lines contrast. It's called `spacemacs-theme-comment-bg` it's on by default, try messing with it in `M-x customize` and see if it helps. Otherwise, I'll try to figure something better.

**Comment by fladd** [comment]
@nashamri Yeah, it would be nice to have a readable and dissociable highlighting right out of the box, without having to mess with `M-x customize`. Concerning the background of the comments, this could also be a bit stronger in general, as it would additionally help to quickly detect comments.
Keep up the great work!

**Comment by nashamri** [comment]
@fladd hey! I made a rather big change to the theme and it can easily now solve this string issue.

Just put this in your `dotspacemacs/user-init`, if you are using spacemacs:
```
  (custom-set-variables '(spacemacs-theme-custom-colors
                          '((str . "#ff0000"))))
```
And customize it as you wish :smile: 
More info https://github.com/nashamri/spacemacs-theme#override-themes-colors
