### ISSUE TITLE
magit help almost unreadable in light theme

### ISSUE THREAD

**Issue by JulienPalard** [nashamri/spacemacs-theme#201]
See:

![Capture d’écran du 2024-04-04 17-17-38](https://github.com/nashamri/spacemacs-theme/assets/239510/d49807e2-5762-4b91-b9f4-19667462326e)

It's barely noticeable but at the left of each command there's the key it maps to, `A` for `Apply`, `b` for `Branch`, `B` for `Bisect`, ...

**Comment by nashamri** [comment]
Hmm?
This is how it looks on my end
![image](https://github.com/nashamri/spacemacs-theme/assets/1207107/5c7ab3b6-0ad2-4d4b-aea3-a7c81708c295)

Did something change in magit?

**Comment by JulienPalard** [comment]
Oh wow it looks nice!!!

Ok a bit of dichotomy in my config file and I found an old `'(frame-background-mode 'dark)` lying around...

sorry for the noise, and thanks **a lot** for this theme, I use it since `Tue Oct 12 07:40:41 2021 +0200` according to `git log` in my dotfile repo :D

**Comment by nashamri** [comment]
@JulienPalard Oh wow, since 2021 :smile: 
I'm glad you like it :+1:
