### ISSUE TITLE
Theme colours are wrong in Emacs Client

### ISSUE THREAD

**Issue by yusi1** [nashamri/spacemacs-theme#204]
Hi I am currently using spacemacs-light in Emacs, works great and looks fantastic but, in emacsclient when emacs is running in server mode the theme does not look right, colours are washed out and isearch results do not have any background colour. How do I fix this and make the theme look the same as when emacs is not running in server mode.

Thanks.

**Comment by nashamri** [comment]
Try something like this in your config:

```elisp
(if (daemonp)
    (add-hook
      'after-make-frame-functions
      (lambda (frame)
        (with-selected-frame frame
           (load-theme 'spacemacs-dark t)))))
```

**Comment by yusi1** [comment]
> Try something like this in your config:
> 
> ```emacs-lisp
> (if (daemonp)
>     (add-hook
>       'after-make-frame-functions
>       (lambda (frame)
>         (with-selected-frame frame
>            (load-theme 'spacemacs-dark t)))))
> ```

Thank you, this worked. I shall close the issue now
