### ISSUE TITLE
[Helm] Marked candidates are not visible

### ISSUE THREAD

**Issue by xuchunyang** [nashamri/spacemacs-theme#22]
For example, here is the screenshot when using GUI Emacs with spacemacs-dark theme enabled (mark first four candidates and select third candidate, i.e., `*Message*`)
![2015-10-06 3 04 28](https://cloud.githubusercontent.com/assets/4550353/10302205/ac1f0e96-6c3c-11e5-9af4-ba03d96433e0.png)

here is the one under the same condition but without using any theme

![2015-10-06 3 05 40](https://cloud.githubusercontent.com/assets/4550353/10302270/5a244178-6c3d-11e5-8555-1072abdabfca.png)

I believe it is affected by `helm-visible-mark` and maybe `helm-selection`.

**Comment by nashamri** [comment]
Yup indeed that one needs a fix. Working on it! thanks for catching this one @xuchunyang :smile:

**Comment by xuchunyang** [comment]
Looks much better! Thanks.

**Comment by nashamri** [comment]
No! thank you for reporting this :+1:
