### ISSUE TITLE
org agenda clocking entry is not visible (that should be `org-agenda-clocking' face)

### ISSUE THREAD

**Issue by xuchunyang** [nashamri/spacemacs-theme#26]
With default theme of graphic Emacs, clocking entry is very obvious (yellow background):

![2015-10-15 11 37 45](https://cloud.githubusercontent.com/assets/4550353/10518965/3d0114b2-7396-11e5-8c75-7896a68c19cc.png)

but with spacemacs-dark, it isn't (actually I don't know which one is clocking):

![2015-10-15 11 38 24](https://cloud.githubusercontent.com/assets/4550353/10519023/6f57bdb2-7396-11e5-8016-603aa5b9ec74.png)

**Comment by nashamri** [comment]
:+1: I'll fix this, thanks @xuchunyang

**Comment by nashamri** [comment]
I'm not an avid org user, so you feedback is important to me. I've noticed that in the screenshot with the default theme, all the entries are normal weight (not bold), where in spacemacs-theme some are bold and some are not. I think that needs some fixing (making all the entries normal), what do you think?

**Comment by xuchunyang** [comment]
Thanks for the fix, it works nicely.

> I've noticed that in the screenshot with the default theme, all the entries are normal weight (not bold), where in spacemacs-theme some are bold and some are not.

Actually I even didn't notice that.

> I think that needs some fixing (making all the entries normal), what do you think?

Agree. Personally I prefer less bold unless it is really necessary, in this case, different types of entries has already stated in different foreground or background colors.

**Comment by xuchunyang** [comment]
> I think that needs some fixing (making all the entries normal),

I have done this in RP #27.

**Comment by nashamri** [comment]
Brilliant! thanks :+1:
