### ISSUE TITLE
Theme for terminals (not related to emacs)

### ISSUE THREAD

**Issue by d12frosted** [nashamri/spacemacs-theme#29]
Hey, I like your themes so much that I want to use them in terminal. So it would be cool to have themes for `Terminal.app`, `iTerm2.app` etc terminal emulators. Probably this is not the right place for this feature request, but since this is the only repo related to `spacemacs-theme`, here we go :smile:

**Comment by nashamri** [comment]
Hey @d12frosted thanks for the kind words :smile: 
That's a good idea, the only problem is that I don't use OS X :smile: 
I might get my hands on a mac soon and play with that.
You can join the gitter room of spacemacs-theme to discuss stuff like this 
https://gitter.im/nashamri/spacemacs-theme

**Comment by d12frosted** [comment]
Ah. I hope that you'll get one soon :smile: 

Oh great, you have a gitter room. Joining!

**Comment by nashamri** [comment]
@d12frosted I got an old macbook air :smile: hopefully I'll make a theme for the terminal app.

**Comment by railwaycat** [comment]
This is an interesting idea.

Not sure for iTerm2, but a Terminal.app theme usually request following colors:

----

Text: text | bold text | selection

ANSI colors(normal and bright): black | red | green | yellow | blue | magenta | cyan | white

Background: background color

Cursor: cursor color

----

text, selection(region in Emacs), cursor and background color could easily found in theme file. 

I think if we are able to fill the rest 16 ANSI colors and then we are done:)

**Comment by gguimaraesbr** [comment]
here: https://github.com/chriskempson/base16-builder/pull/345

**Comment by nashamri** [comment]
@gguimaraesbr that's great :smile: :+1: thanks for this!

**Comment by nashamri** [comment]
@gguimaraesbr how about making 2 of these :smile: one for the dark variant and one for the light variant?

**Comment by gguimaraesbr** [comment]
@nashamri actually it's already provided by the base16-builder itself (each scheme creates both variants).

**Comment by nashamri** [comment]
@gguimaraesbr Super! thanks a lot for this :smile: but I'm wondering how it can achieve this? if it inverts some of the colors to get the other variant, then the result might not be similar to spacemacs-theme. Because the variants aren't the exact inverse of each other.

**Comment by nashamri** [comment]
![base16](https://cloud.githubusercontent.com/assets/1207107/13301484/0ea7195e-db3d-11e5-8578-b5ff23346dbc.png)
I managed to run it and install gnome-terminal profile. The dark vairant is great and the light one is almost there :smile: the background color is a bit off (see the screenshot :point_up_2:) but I don't think this is a big deal since that tool supports that many applications.

**Comment by nashamri** [comment]
![base16-2](https://cloud.githubusercontent.com/assets/1207107/13301811/b7f677d8-db3e-11e5-9873-d5880641927d.png)
Actually it's quite similar to spacemacs-light when using spacemacs in the terminal. So scratch what I said about the background being a bit off :+1: well done.

**Comment by gguimaraesbr** [comment]
Thanks! I tried to be loyal to the colors you used but base16-builder has its own way to generate the output files. The upside is that it supports a lots of tools... ;)

**Comment by nashamri** [comment]
@gguimaraesbr PR got merged in this fork https://github.com/auduchinok/base16-builder
So I think we can close this issue now :+1:
Thanks everyone!

**Comment by d12frosted** [comment]
@nashamri nice! thanks for the themes.

**Comment by lpil** [comment]
Great. Thank you!
