### ISSUE TITLE
Is there any simple way to customize some colors?

### ISSUE THREAD

**Issue by dotneter-** [nashamri/spacemacs-theme#30]
I would like to change some colors, something like

```
(custome-colors-spacemacs-theme (bg1 "#000000"))
```
Can I somehow do this?

**Comment by nashamri** [comment]
Maybe you could do something like this in your `.spacemacs` file (I'm assuming you are using spacemacs :) )
`(custom-theme-set-faces 'spacemacs-dark '(default ((t (:background "#ff0000")))))`

where `default` is the face you want to change.

**Comment by dotneter-** [comment]
I don't want to change the faces. I want to use this theme's infrastructure and change only its colors, so it can use them to change faces.

**Comment by nashamri** [comment]
Oh I see. I'm not sure that's possible currently since all the colors are locally bounded in the `create-spacemacs-theme` function. I'll report back here if I found anything useful or if I could implement something to make this possible.

**Comment by dotneter-** [comment]
I am not really good with lisp, but I think it could be implemented like this

```
var dictionaryWithColors = {
      base : ["#d9d9d9", "#b2b2b2", "#655370", "#5f5f87"]
      cursor:["#e3dedd", "#d0d0d0", "#100a14", "#121212"]     
      ...
}

function customColors(userDictionaryWithCustomColors){
      dictionaryWithColors = merge(dictionaryWithColors, userDictionaryWithCustomColors);
}
```
and I can use dictionaryWithColors in ```create-spacemacs-theme```

**Comment by nashamri** [comment]
I think I found a way to achieve that and it should be as simple as calling a function and pass in a list of colors that you want to override. I just want to double check the new code to make sure it's not breaking anything. Stay tuned :smile:

**Comment by nashamri** [comment]
Sorry it took me sometime to do this. But I did a some what major change and refactoring and cleaning.
Just check https://github.com/nashamri/spacemacs-theme#override-themes-colors to achieve exactly what you requested :smile:

**Comment by dotneter-** [comment]
It works, thanks.

**Comment by dotneter-** [comment]
Is it possible to apply changes of ```spacemacs-theme-custom-colors``` without restarting emacs?

**Comment by nashamri** [comment]
@dotneter- if you want to experiment with the changes without restarting emacs, I think you can do the following:

1- Open up the `spacemacs-common.el` file which is part of spacemacs-theme package. You'll find it in your `~/.emacs.d/elpa/spacemacs-theme-xxxxxxxxx` folder.
2- Open a scratch buffer and set it to `emacs-lisp-mode`
3- Type something like this `(custom-set-variables '(spacemacs-theme-custom-colors '((bg1 . "#000000"))))` and evaluate it.
4- Go back to the  `spacemacs-common.el` and evaluate the buffer.
5- Switch to the theme (in spacemacs `SPC T h` then type theme name).
6- Check the changes and if you don't like it, repeat from step 3.

**Comment by dotneter-** [comment]
thanks
