### ISSUE TITLE
Flycheck tooltip flickers white before showing error.

### ISSUE THREAD

**Issue by jordwalke** [nashamri/spacemacs-theme#31]
On dark colorschemes, the flycheck tooltip flickers white momentarily before showing the more pleasing colors. It's very distracting. Do you know what's causing this?

(I'm using the mac port of emacs).

**Comment by jordwalke** [comment]
Note, this is only with `flycheck-pos-tip`.

**Comment by nashamri** [comment]
Does this only happen with `spacemacs-dark`? Could it be related to this https://github.com/nashamri/spacemacs-theme/issues/11?

**Comment by nashamri** [comment]
@jordwalke Is this still an issue?
