### ISSUE TITLE
Theme looks weird in terminal

### ISSUE THREAD

**Issue by bogdanteleaga** [nashamri/spacemacs-theme#32]
Hey,

Spacemacs is getting more and more usable in terminal mode and I got used to this theme, but it shows some problem when ran in terminals. I'll attach some pictures.

![Spacemacs Dark](https://i.imgur.com/xERAS5V.jpg)
![Monokai](https://i.imgur.com/bTxe3ne.jpg)

Probably worth it to mention I'm using this code to get transparency
```
(defun remove-background-color ()
  "Useful for transparent terminal."
  (unless (display-graphic-p (selected-frame))
    (set-face-background 'default "unspecified-bg" (selected-frame))))
```

I did try to restart it and the top line changes from blue to a greyish black, however the comments are what gets really annoying.

Ideas?

**Comment by nashamri** [comment]
From the screenshots it seems like the problem is only in the comment lines.
Maybe if you turn off the comment line background it will fix the issue. 
https://github.com/nashamri/spacemacs-theme#customization
Just set `spacemacs-theme-comment-bg` to `nil`

**Comment by bogdanteleaga** [comment]
Nope, that doesn't do it.

**Comment by nashamri** [comment]
Oh okay :smile: I'll look into it tomorrow, hopefully.
Are you running OS X? and what's your terminal emulator?

**Comment by bogdanteleaga** [comment]
Hmm, I changed something in the code I pasted above and it seems to work correctly now. All I did was make it take frame as an argument instead of calling selected-frame inside. But it works! The wonders of software :)

Thanks for the fast replies though.

**Comment by nashamri** [comment]
hehe okay awesome! happy hacking!
