### ISSUE TITLE
Support for swiper/ivy faces

### ISSUE THREAD

**Issue by syl20bnr** [nashamri/spacemacs-theme#34]
Spacemacs now supports Ivy, the default blueish colors are not very readable.

Note: Ivy blends the colors of the highlight (i.e. when doing a search with SPC /) and the current line.

**Comment by nashamri** [comment]
I'm not sure if supporting ivy implies supporting swiper or not :smile: so I'm leaving this open till I do better testing.

**Comment by syl20bnr** [comment]
Oops I meant swiper yes, my bad.

There is an issue with the new colors, I suggest to use the background colors and find some colors that blend well together. Without the background color it makes it hard to see the occurrences with `SPC s s` like in the screenshot below:

![capture d ecran 2016-01-10 a 21 49 01](https://cloud.githubusercontent.com/assets/1243537/12226073/4bef57c6-b7e4-11e5-91b0-dbe121ea38dd.png)

Also I would prefer to still be able to see the highlighted occurences in the current line but this is a personal preference.

**Comment by nashamri** [comment]
Oh, are you talking about these colors? (highlighted in red)

![4bef57c6-b7e4-11e5-91b0-dbe121ea38dd](https://cloud.githubusercontent.com/assets/1207107/12277083/7e9cd250-b971-11e5-8cf8-076121261841.png)

This week and probably the next one are a bit busy for me, so sorry for the late responses :smile:

**Comment by nashamri** [comment]
There are a lot of inconsistencies between the different searching packages. This needs an overhaul :smile:

**Comment by syl20bnr** [comment]
Nope I mean the one in the swiper mini buffer. Actually I'm asking for
background colors like in the upper buffer (and like default swiper faces)

Le mardi 12 janvier 2016, Nasser Alshammari <notifications@github.com> a
écrit :

> Oh, are you talking about these colors? (highlighted in red)
>
> [image: 4bef57c6-b7e4-11e5-91b0-dbe121ea38dd]
> <https://cloud.githubusercontent.com/assets/1207107/12277083/7e9cd250-b971-11e5-8cf8-076121261841.png>
>
> This week and probably the next one are a bit busy for me, so sorry for
> the late responses [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nashamri/spacemacs-theme/issues/34#issuecomment-171057049>
> .
>


-- 
-syl20bnr-

**Comment by nashamri** [comment]
Now it should be fix :smile: @syl20bnr let me know if you think it's still not fully solved.

**Comment by nashamri** [comment]
Something I noticed from the screen shot, you have rainbow delimiters on. It might be interfering with swiper.

**Comment by syl20bnr** [comment]
It's OK with your last modifications, I pushed a tweak in Spacemacs to remove the blending performed by Ivy because with the dark variant it was hiding occurrences in the current line.

I feel that there is too much contrast for the current line faces with `mat` and `bg3`, but I tweaked the colors during 3 hours yesterday and I did not find anything satisfying!

Thanks for the updates :+1:

**Comment by nashamri** [comment]
Tweaking these things is a real time sink :smile: I'll probably give it another go.

**Comment by syl20bnr** [comment]
There are some regressions with the last modifications:

evil persistent highlighting is yellow:

![capture d ecran 2016-01-17 a 11 18 21](https://cloud.githubusercontent.com/assets/1243537/12378456/1d3d960e-bd0c-11e5-95d3-5a54c2b9e010.png)

In helm the current line make it hard to see the occurrence:

![capture d ecran 2016-01-17 a 11 19 28](https://cloud.githubusercontent.com/assets/1243537/12378460/3a411212-bd0c-11e5-96f6-e52362997617.png)

**Comment by nashamri** [comment]
@syl20bnr just pushed an update that should make the situation a bit better. I'm not sure why evil persistent highlighting looked like that. It should only change the background color to `highlight`.

**Comment by syl20bnr** [comment]
:purple_heart:

**Comment by nashamri** [comment]
I gave this another shot :smile: and this is the results so far, which one do you think is better? Underlined or not?

![d](https://cloud.githubusercontent.com/assets/1207107/12493683/08b6c60e-c07e-11e5-8ebd-611bc0a933f8.png)
![dark](https://cloud.githubusercontent.com/assets/1207107/12493681/08b57dd0-c07e-11e5-94d3-517e4c7f67e8.png)
![l](https://cloud.githubusercontent.com/assets/1207107/12493682/08b6474c-c07e-11e5-9a4d-62813a890a55.png)
![light](https://cloud.githubusercontent.com/assets/1207107/12493684/08ba3212-c07e-11e5-8ab2-f7bc7e10d535.png)

**Comment by syl20bnr** [comment]
Wow it's really nice! I prefer with the underline, it allows to remove some
possible ambiguity.

Great job!

Le jeudi 21 janvier 2016, Nasser Alshammari <notifications@github.com> a
écrit :

> I gave this another shot [image: :smile:] and this is the results so far,
> which one do you think is better? Underlined or not?
>
> [image: d]
> <https://cloud.githubusercontent.com/assets/1207107/12493683/08b6c60e-c07e-11e5-8ebd-611bc0a933f8.png>
> [image: dark]
> <https://cloud.githubusercontent.com/assets/1207107/12493681/08b57dd0-c07e-11e5-94d3-517e4c7f67e8.png>
> [image: l]
> <https://cloud.githubusercontent.com/assets/1207107/12493682/08b6474c-c07e-11e5-9a4d-62813a890a55.png>
> [image: light]
> <https://cloud.githubusercontent.com/assets/1207107/12493684/08ba3212-c07e-11e5-8ab2-f7bc7e10d535.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nashamri/spacemacs-theme/issues/34#issuecomment-173700043>
> .
>


-- 
-syl20bnr-

**Comment by nashamri** [comment]
The underlined one it is! It was the one that I thought the most readable.

**Comment by nashamri** [comment]
@syl20bnr I think this one is resolved :smile: I'm going to close it for now, but don't hesitate to comment on it if something comes up.

**Comment by syl20bnr** [comment]
Thank you !
