### ISSUE TITLE
emacslient background

### ISSUE THREAD

**Issue by scloudyy** [nashamri/spacemacs-theme#35]
I use spacemacs with spacemacs-dark, and when use "emacsclient -t" in terimal, the darkground is too dark, so which variable should I modify to change the background? I have tried bg1, bg2, bg3, bg4, but they all useless.
![qq 20160128220938](https://cloud.githubusercontent.com/assets/15358886/12646603/0f0b9faa-c60c-11e5-85fc-0ea44deac678.png)

**Comment by scloudyy** [comment]
I read the src code just now, and notice that the GUI and terminal has the different color, so , how can I override terminal color in dotspacemacs/user-init ()? @nashamri

**Comment by nashamri** [comment]
Hey @scloudyy,
Have you tried this https://github.com/nashamri/spacemacs-theme#override-themes-colors
I think you only need to override `bg1`. So basically, something like this:
`(custom-set-variables '(spacemacs-theme-custom-colors
                          '((bg1 . "#222222"))))`

**Comment by scloudyy** [comment]
Yes, I have tried, but it seems doesn't. If I change bg1 to green, something under the background is changed to green, but background is still black, bg3, bg4 all the same.
![qq 20160129092853](https://cloud.githubusercontent.com/assets/15358886/12664530/36c315c8-c66b-11e5-82e7-b3face5875bd.png)

**Comment by nashamri** [comment]
Okay that's weird :smile: I'll look into it tonight.

**Comment by scloudyy** [comment]
@nashamri 
Is there any results of this problem? Or do you need more information?

#### System Info
- OS: gnu/linux
- Emacs: 24.5.3
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. 72e1413)
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(spacemacs-ivy spacemacs-helm better-defaults semantic markdown org search-engine
               (syntax-checking :variables syntax-checking-enable-tooltips nil syntax-checking-enable-by-default t)
               python emacs-lisp ycmd gtags
               (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
               (ibuffer :variables ibuffer-group-buffers-by 'projects)
               (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
               (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup nil)
               (shell :variables shell-default-height 50 shell-default-shell 'eshell shell-default-term-shell "/bin/zsh" shell-enable-smart-eshell t)
               (chinese :variables chinese-default-input-method 'pinyin chinese-enable-youdao-dict t chinese-enable-fcitx t)
               prodigy ranger spacemacs-layouts extra-langs fasd pandoc
               (elfeed :variables rmh-elfeed-org-files
                       (list "~/.spacemacs.d/elfeed.org"))
               deft
               (clojure :variables clojure-enable-fancify-symbols t)
               unimpaired html scloudyy)
```

Put this code to dotspacemacs/user-init()
```
(defun dotspacemacs/user-init ()
  "Initialization function for user code.
It is called immediately after `dotspacemacs/init'.  You are free to put any
user code."
  (custom-set-variables '(spacemacs-theme-custom-colors
                          '((bg1 . "#66ff00"))))
```
At the begining of load
![qq 20160130220234](https://cloud.githubusercontent.com/assets/15358886/12696155/ad3d89ee-c79d-11e5-86ba-e2974c0bb8e2.png)

And when everything is loaded
![qq 20160130220244](https://cloud.githubusercontent.com/assets/15358886/12696158/bb3d4282-c79d-11e5-808d-f6179def78d5.png)
 To be honest, I don't like green, just for experiment.

**Comment by nashamri** [comment]
Thanks @scloudyy for the additional info. I'm not sure why it's behaving like this with you. I tried it on my end and it working fine.

![screenshot from 2016-01-30 20-43-32](https://cloud.githubusercontent.com/assets/1207107/12698340/4b1301e6-c792-11e5-8e96-ddcb089a20b3.png)

Can you try running this in your shell before starting `emacsclient -t`:
`export TERM='xterm-256color'`

Sorry for being late, things are a bit crazy lately :smile:

**Comment by scloudyy** [comment]
After I reinstalled my spacemacs, it seems fine now!
Thank you for your help! @nashamri

**Comment by nashamri** [comment]
Oh great! @scloudyy 
Happy spacemacsing with custom colors! :smile:
