### ISSUE TITLE
bold t vs inherit bold

### ISSUE THREAD

**Issue by rougier** [nashamri/spacemacs-theme#37]
Would it be possible to replace all the `:bold t` and `:weight bold` by `:inherit bold`?

I'm using "Source Code Pro Light" for the main font and thus the bold face is "Source Code Pro Regular". Being able to specify the `bold` face for all faces that use it would be great. I can make a PR if necessary.

I think it won't change anything visually unless someone changed the `bold` face.

**Comment by nashamri** [comment]
@rougier Yeah sure, this seems like a good idea. Let me experiment with it a bit and I'll push an update :smile:

**Comment by nashamri** [comment]
@rougier Everything seems fine with this change. If you are using the package through MELPA, just give it a moment to be picked up.

**Comment by rougier** [comment]
Nice, thank you.
