### ISSUE TITLE
dark theme :s face

### ISSUE THREAD

**Issue by darkfeline** [nashamri/spacemacs-theme#40]
When doing a `:s/foo/bar/` style command, Evil will highlight both the deleted and replacement text accordingly. However, the deleted text isn't visibly changed when using Spacemacs's dark theme.

This is only a problem if you use visual mode to select text and use `:<',>'s` because the visual selection face is the same as the deleted text preview.

Simply doing a `:%s`, for example, this isn't a problem.

**Comment by nashamri** [comment]
![bug40](https://cloud.githubusercontent.com/assets/1207107/13379055/4194dc06-de13-11e5-9b6b-1f6e463c0c3d.png)

Thanks for reporting this @darkfeline I think I fixed it now. Wait for MELPA to reflect the changes.
