### ISSUE TITLE
Region selection and search highlight

### ISSUE THREAD

**Issue by user471** [nashamri/spacemacs-theme#41]
If you search `/foo`, it would be highlighted like this
![1](https://cloud.githubusercontent.com/assets/5988253/13380206/a2628cbe-de4e-11e5-929e-a7796a9245d1.png)
But region selection have the same color, so highlights aren't visible.

![2](https://cloud.githubusercontent.com/assets/5988253/13380210/a5d36a4e-de4e-11e5-9d7e-3801e4fb1810.png)

The main problem is replacing in region. When you select the region and then try to use `:'<,'>s/foo/` you cannot see the `foo` highlight.

**Comment by nashamri** [comment]
Hey @user471 this has already been fixed in #40.
Just give it a minute so that MELPA pick up the fix.

**Comment by user471** [comment]
thanks
