### ISSUE TITLE
Cannot load spacemacs-theme by use-package

### ISSUE THREAD

**Issue by zzp0** [nashamri/spacemacs-theme#42]
```
(use-package spacemacs-theme
  :config
  (load-theme 'spacemacs-dark t))
```
*Messages buffer* shows `Cannot load spacemacs-theme`
p.s. I just use *emacs-mac port* without *spacemacs kit*

**Comment by xuchunyang** [comment]
You can use the following instead:

```
(use-package spacemacs-theme
  :defer t
  :init (load-theme 'spacemacs-dark t))
```

`:defer t` will prevent requiring `spacemacs-theme`, which doesn't exist, `:config ...` will run some code after `spacemacs-theme` (a non-existent feature) is required.  And since `use-package` doesn't look very meaningful here, also consider to just use `(load-theme 'spacemacs-dark t)`.

**Comment by zzp0** [comment]
@xuchunyang Thank you for your reply. But it didn't work, theme not loading completely, using default theme instead.

**Comment by xuchunyang** [comment]
> theme not loading completely, using default theme instead.

Did you mean something like this?

![screen shot 2016-03-04 at 22 18 43](https://cloud.githubusercontent.com/assets/4550353/13529445/38f935e0-e257-11e5-9d63-fcf7bde0aef3.png)

I encounter this if I have `desktop-save-mode` on and enable spacemacs-dark from init.el but then disable it in Custom Themes (M-x customize-themes).

**Comment by agsdot** [comment]
@xuchunyang and @zzp0 , I'm finding that 

```
(use-package spacemacs-theme
  :defer t
  :init (load-theme 'spacemacs-dark t))
```

also doesn't work. @zzp0 did you get it to work in your setup? @xuchunyang I don't have desktop-save-mode in my emacs.d . 

I just want to use the spacemacs-theme right now, without using the entire spacemacs .emacs.d config . I like how the spacemancs-theme displays in the terminal, whereas some other themes don't display as nicely (e.g. solarized).

**Comment by agsdot** [comment]
Nevermind. I accidentally was applying two themes at the same time. Later on in my .emacs.d, I was applying another theme. Sorry, @xuchunyang , your original code suggestion works just fine. Thanks!

**Comment by swarnendubiswas** [comment]
Another option is:
```
(use-package spacemacs-common
    :ensure spacemacs-theme
    :config (load-theme 'spacemacs-light t))
```

**Comment by idanko** [comment]
**Update Jan 14 2022**
I'm not a spacemacs user and load the package using use-package and straight.el as package manager. After all advice have applied from this thread, I still experience errors like this `(error "Package ‘spacemacs-theme-’ is unavailable")`. Tired from both: a regular and client instance (emacsclient -c).

I came up to the following workaround:
```lisp
(use-package spacemacs-theme
  :straight t
  :defer t
  :init (load-theme 'spacemacs-light t))

(add-hook 'after-make-frame-functions
	      (lambda (&optional frame)
            (when frame
              (select-frame frame))
            (load-theme 'spacemacs-light t)))
```
This way it works for both: a client and a regular Emacs instance.

PS: `:straight t` is not necessary.

**Comment by nashamri** [comment]
I think this now works too:
```elisp
(use-package spacemacs-theme
  :defer t
  :init (load-theme 'spacemacs-dark t))
```

**Comment by kuhlekt1v** [comment]
This works in 2023

```
(use-package spacemacs-theme
  :ensure t
  :config
  (load-theme 'spacemacs-dark t))
```
