### ISSUE TITLE
custom-set-variables changes both dark and light themes

### ISSUE THREAD

**Issue by adrsta** [nashamri/spacemacs-theme#43]
I like both spacemacs themes a lot, and I use them interchangeably.
My only problem is that the background in the dark theme is too light.
So I have put this in my spacemacs/user-init():  (according to the README)
```
 (custom-set-variables '(spacemacs-theme-custom-colors
                          '((bg1 . "#141516")
                            (bg2 . "#100913")
                            (comment-bg . "#14151A"))))
```
And it solves the problem, but also creates another one because the light theme has the same dark background now :(

**Comment by nashamri** [comment]
@adrsta glad you like the themes :smile:
The issue that you are having isn't a bug, it's the current implementation and you are right, it causes a problem when you are using both themes. I'll try to figure something out about this :+1: 
Thanks for reporting this! :smile:

**Comment by adrsta** [comment]
I figured another way (maybe you can recomment that in the README).

I used `theming` layer from spacemacs, and put code below in my dotspacemacs/user-init()
```
  (setq theming-modifications '((spacemacs-dark (default :background "#141516")
                                                (hl-line :background "#100913")
                                                (font-lock-comment-face :background "#14151A"))))
```
Now it's perfect ;]

**Comment by nashamri** [comment]
Oh that's great I'll add that to the README :+1: 
It still bypasses the theme though, and set the faces directly. Which is fine, but you have to do that for all the faces and modes you like to change.
