### ISSUE TITLE
Spacesmacs screenshots don't have same faces.

### ISSUE THREAD

**Issue by jojojames** [nashamri/spacemacs-theme#44]
https://github.com/nashamri/spacemacs-theme/blob/screenshots/org.png

The Headline faces don't seem to be the same.
<img width="693" alt="screenshot 2016-03-30 13 46 48" src="https://cloud.githubusercontent.com/assets/1227856/14156965/e47122cc-f67d-11e5-8871-8bd22db905dd.png">

**Comment by nashamri** [comment]
Are you talking about the bullet points not looking the same?
If that's the case, make sure you have [org-bullets](https://github.com/sabof/org-bullets) installed and activated.

**Comment by jojojames** [comment]
Thanks, that was it.

**Comment by nashamri** [comment]
Cheers! :smile:
