### ISSUE TITLE
Coloring of mu4e

### ISSUE THREAD

**Issue by jabranham** [nashamri/spacemacs-theme#45]
Hi - 

Thanks for the great theme. 

In `mu4e-headers`, the color of an email that I've replied to is the same as an email I haven't read yet. Is it possible to fix that? I know basically nothing about how emacs themes work, otherwise I'd do it myself...

**Comment by nashamri** [comment]
Hey @jabranham I'm glad you like the theme :smile: 
For sure this can be fixed, but I didn't use mu4e before. This certainly is on my todo list. I'll keep this issue open until I fix it.
Cheers!

**Comment by jabranham** [comment]
In case anyone else is wondering about this, you can fix it fairly easily. Here is the whole setup I'm currently using for spacemacs-theme:
```
(use-package spacemacs-theme
  :ensure t
  :defer t
  :init
  (load-theme 'spacemacs-dark t)
  (custom-set-faces
   '(mu4e-unread-face ((t (:inherit font-lock-keyword-face :foreground "yellow" :weight bold))))))
```

That makes unread emails yellow and bold, but you can obviously customize that to whatever.

**Comment by nashamri** [comment]
Hey @jabranham sorry for being late :smile: . I still didn't use mu4e but I pushed a small commit based on your snippet. Please leave this issue open until I get the time to theme all of mu4e.
