### ISSUE TITLE
Symbols in ruby erb hard to read in light mode

### ISSUE THREAD

**Issue by chrismcg** [nashamri/spacemacs-theme#49]
I love pretty much everything about your themes, thanks! The only thing is having to switch to -dark when editing .erb files because symbols are hard to read. I don't know enough about how themes work yet to figure out how to tweak or send a PR.

![index_html_erb](https://cloud.githubusercontent.com/assets/212/16036242/e8194be0-3212-11e6-9019-c2fb8d502702.png)

**Comment by nashamri** [comment]
@chrismcg Thanks :smile: 
yeah that yellow symbol needs some tweaking. I'll fix it right away.

**Comment by nashamri** [comment]
It should be good now. Wait for MELPA to update then if everything is fine, you can close this issue :smile: 
Thanks for reporting this one!

**Comment by chrismcg** [comment]
Much easier to read now, thanks again!
