### ISSUE TITLE
set spacemacs colors into ansi-color-names-vector

### ISSUE THREAD

**Issue by benswift** [nashamri/spacemacs-theme#50]
Currently, spacemacs-theme doesn't touch `ansi-color-names-vector`, which means that for certain colored terminal output (e.g. in `async-shell-command` or `eshell`) the colored output is hard to read against the spacemacs dark background color.

[Monokai updates that vector](https://github.com/oneKelvinSmith/monokai-emacs/blob/master/monokai-theme.el#L5682), I'm wondering if it's possible for spacemacs theme to do something similar, e.g.
```elisp
`(ansi-color-names-vector [,bg4 ,red ,green ,yellow ,blue ,magenta ,cyan ,base])
```
although this would involve some surgery to the `dyn-let` approach, since it has to be inside a `custom-theme-set-variables` instead of a `custom-theme-set-faces`.  What do you reckon?

**Comment by nashamri** [comment]
Hey @benswift :smile: 

We can modify `dyn-let` to be something like this:
```elisp
(defmacro dyn-let (varlist fn body setvars)
  (list 'let (append varlist (funcall fn)) body setvars))
```
and then append the call to `custom-theme-set-variables`.

I quickly tried it and it worked I just need to play with this a bit more just to make sure everything is fine.

Here's a gist of that change for you to check out:
https://gist.github.com/nashamri/6074115278bdf056636b0e010eb740bc

**Comment by benswift** [comment]
Sure, sounds good. Alternately, could you change `dyn-let` to take
```elisp
(varlist fn &rest body)
```
then you're covered for the more general case of multiplie body forms,
rather than just the two?  Still, the other option is fine too. I'm also
not sure which colours you want to use, you know the "spacemacs-y feel"
mappings better than I :)

**Comment by nashamri** [comment]
You are right `(varlist fn &rest body)` would be the general case but I don't see me doing anything else other than setting faces and variables. So doing it the more specific way would maybe make the code more readable. I'm going to push this change now and let me know if anything goes bad :smile:

**Comment by benswift** [comment]
Sure, that's fine.  I'm a sucker for over-engineering things, but you're
right that there probably won't be the need for a more general solution
here.

**Comment by nashamri** [comment]
All righty, this one seems done. Feel free to re-open it if you notice something wrong.
