### ISSUE TITLE
Color the entire gutter

### ISSUE THREAD

**Issue by Stebalien** [nashamri/spacemacs-theme#53]
#52 changed the fringe background color to match the gutter. Unfortunately, introduces some ugly corner cases:

![1467828835](https://cloud.githubusercontent.com/assets/310393/16629702/d889aa66-4384-11e6-9872-d30008c9f9ce.png)
1. Not all parts of the gutter are colored. This creates ugly boxes.
2. There's an ugly disconnect between the fringe line in the buffer and the fringe line in the command prompt.

One solution is to revert #52 but, IMO, a better solution is to try to find a way to color the entire gutter. Is this possible?

**Comment by nashamri** [comment]
Thank you @Stebalien :smile:  I've reverted the last PR.

I like having a bit of contrast between the line numbers and the actual buffer because if the fringe is turned off, the line numbers will be really close to the buffer. The fringe, on the other hand, does extend past the line numbers (linum-mode) as you show in your figure (#2). So for now, I think the fringe should have the same background color as the buffer.

Maybe if something could be done upstream in linum-mode, because I noticed the same issue on other themes (e.g. leuven).

**Comment by belak** [comment]
I really don't like how this looks with `linum-mode`. Having a buffer at the start of the line that's the same color as the code can make it unclear how much space is actually at the start of the line.

For me, this is a question of whether the fringe "belongs" to the code or something else. I view it as something separate, but that might just be me.

That being said, I'm not sure if there's a fix for the issues mentioned. Even themes like `zenburn` and the `base16` set seem to have the same problems.

Alternatively, would you consider something like what zenburn has (`zenburn-with-color-variables` https://github.com/bbatsov/zenburn-emacs/blob/master/zenburn-theme.el#L91) but for the spacemacs colors so I can tweak stuff like this without having to copy the exact colors?

**Comment by Stebalien** [comment]
You can partially fix this (https://emacs.stackexchange.com/questions/805/how-can-i-fill-the-entire-line-number-bar-with-a-custom-background-color) but this fix introduces some supposedly fixable performance issues.

Personally, I prefer just leaving the space as is. The numbers are right aligned so I know there will always be exactly one space between the line numbers and the text.

**Comment by Stebalien** [comment]
However, I'd love to have a way to configure this.

**Comment by nashamri** [comment]
@Stebalien is this still an issue? I've just tried the `develop` branch of spacemacs and it seems the issue is gone, as shown in the screenshot below:
![archlabs_2018-01-07-28_1920x1080](https://user-images.githubusercontent.com/1207107/34652823-6aaca74c-f3f4-11e7-9db5-d036acfd0db4.png)

**Comment by Stebalien** [comment]
Sorry, forgot to close. Thanks!
