### ISSUE TITLE
improve avy highlighting in terminal

### ISSUE THREAD

**Issue by ninrod** [nashamri/spacemacs-theme#54]
right now, when using the theme inside the terminal, it's very hard to see the right sequence that the user needs to hit when using avy. Sample below:

![screenshot](https://cloud.githubusercontent.com/assets/8352747/16792385/577eec6e-489e-11e6-9fca-7ddc718ca016.png)

ref: https://github.com/syl20bnr/spacemacs/issues/6564

**Comment by nashamri** [comment]
@ninrod Thank you for reporting this. It's fixed now. Just wait for MELPA to update :smile: :+1:
