### ISSUE TITLE
Consider changing color for face lazy-highlight

### ISSUE THREAD

**Issue by syl20bnr** [nashamri/spacemacs-theme#55]
Hi Nasser,

I just pushed https://github.com/syl20bnr/spacemacs/commit/653da2a to develop branch. It tries to keep consistency with smartparens overlay and evil search highlight.
I did this to make it easier to fix an annoying UX bug which is that overlayed pairs or evil persistent search occurrences have the same face as `region`. It is very uncomfortable when you want to select the text since you cannot tell the difference between the text and the selected text.

So I unified those faces by making them inherit from `lazy-highlight` which should be a good default. The idea is to find a good color for `lazy-highlight` which is not the same as `region` or maybe `highlight`.

**Comment by nashamri** [comment]
Oh this is great! and it might fix this old issue https://github.com/nashamri/spacemacs-theme/issues/25
Working on it!

**Comment by nashamri** [comment]
@syl20bnr this https://github.com/nashamri/spacemacs-theme/commit/b61aface0a62b24cbfd47de3ea393885e7a9f1ae looks good on my end, tell me if you see any issues :smile:

**Comment by syl20bnr** [comment]
@nashamri just tested it! Great job! :purple_heart:
