### ISSUE TITLE
Standardize headers

### ISSUE THREAD

**Issue by jabranham** [nashamri/spacemacs-theme#58]
It would be nice if headings across different modes were standardized (color, height, etc). For example, right now org-mode and markdown-mode headers (and sub-headers, and sub-sub-headers) are the same color but different heights. Latex (sub/sub)headers are a different color, but the same (or similar) height as org-mode.

**Comment by nashamri** [comment]
Hey @jabranham :smile: 
Yeah you are right, I'll fix it.
