### ISSUE TITLE
Theme additions for Jabber

### ISSUE THREAD

**Issue by peterhadlaw** [nashamri/spacemacs-theme#59]
Great project, really happy user. I'm gonna make an issue about this theme not having support for jabber.el

As a reference, here is bbatsov's [implementation](https://github.com/bbatsov/solarized-emacs/blob/37cb827e62d37e664ea7b46ef26927fd399a819a/solarized.el#L1160) for his solarized-theme. 

When I can, I'll loop back with a PR adding support for this

**Comment by nashamri** [comment]
Hey @peterhadlaw :smile: 
Thanks for reporting this and linking to bbatsov's take on it. I'll probably get sometime to do it tomorrow, hopefully.

**Comment by nashamri** [comment]
All done, wait for melpa and let me know if you see something wrong with it :beers:

**Comment by peterhadlaw** [comment]
@nashamri This looks great!! Thank you so much for adding this :) 👍 Gonna be using it every day
