### ISSUE TITLE
Line is too close in Top-Level Face in Org when it is a TODO

### ISSUE THREAD

**Issue by travisbhartwell** [nashamri/spacemacs-theme#6]
I like the line above top-level items in org-mode.  But it is a little too close when that item is a TODO, as  shown in this screenshot:
![org-mode](https://cloud.githubusercontent.com/assets/10110/8513671/ec03591c-2331-11e5-82a9-d7aa2e52a927.png)

Since the face used for the word TODO or DONE is slightly larger than the rest of the text, it runs into the line and there is a noticeable line break.  The line above top level items should therefore be slightly higher.

I'm using the standard Spacemacs font and size, on Linux, in Emacs 24.5.

**Comment by nashamri** [comment]
Thanks @travisbhartwell for this. I hope you like the new commit :smile:

**Comment by nashamri** [comment]
However, another issue that I saw in your screenshot is: the +strike-through+ markup in any heading doesn't respect the style of that heading. I tried other markup (like ~code~ /italic/) and they seem to work as expected. It's only the struck through words. It seems to be a deeper issue not related to the theme after my initial investigation. It could be an issue with Emacs itself.
