### ISSUE TITLE
The search highlight is almost invisible in the develop branch

### ISSUE THREAD

**Issue by duianto** [nashamri/spacemacs-theme#60]
#### Description :octocat:

In the spacemacs develop branch, the spacemacs-dark-themes search highlight background color: `#293239`, and the emacs background color: `#292E34` are to similar. That makes the highlight pretty much invisible.

A quick check showed that the highlight color also is to similar to the background color in the spacemacs-light-theme.

The highlight color is a lot more visible in the spacemacs master branch (only the dark theme was checked in master).

#### Reproduction guide :beetle:

Start Emacs
Open .spacemacs <kbd>SPC f e d</kbd>
Search for the word "the" with either: <kbd>C-s</kbd> `the` <kbd>RET</kbd> , `/the` <kbd>RET</kbd> or `?the` <kbd>RET</kbd>

#### With the spacemacs-dark-theme:
All visible instances of the word "the" gets highlighted.

In the Spacemacs branch: develop (rev. 89137bb)
The highlight is pretty much invisible, the text background color is: `#293239`

The highlight is visible in the master branch:
Spacemacs branch: master (rev. 9f9faa4)
There the text background color is: `#444155`

In both the master and develop branch, the emacs background color is the same: `#292E34`

#### Expected behaviour: :heart: :smile:

The highlight color should be more visible in the develop branch.

System Info :computer:

OS: windows-nt
Emacs: 24.5.1
Spacemacs: 0.105.22
Spacemacs branch: develop (rev. 89137bb)
Graphic display: t
Distribution: spacemacs
Editing style: vim
Completion: helm
Layers:
```
(helm emacs-lisp git)
```

**Comment by nashamri** [comment]
Hey @duianto thanks for reporting this :smile: 
This is related to this issue https://github.com/nashamri/spacemacs-theme/issues/55

**Comment by nashamri** [comment]
So, from what I can see, this commit https://github.com/syl20bnr/spacemacs/commit/653da2a
kinda unified the face `evil-search-highlight-persist-highlight-face` (the one used when you `C-s`) and the face `sp-pair-overlay-face` (used when opening a paren to highlight the paren region) to inherit from the face `lazy-highlight`.

If we break the unification and made `evil-search-highlight-persist-highlight-face` not to inherit form `lazy-highlight` and themed it individually, will this cause an issue that the commit https://github.com/syl20bnr/spacemacs/commit/653da2a fixed?

pinging @syl20bnr

**Comment by syl20bnr** [comment]
Maybe find another color for `lazy-highlight` then. The idea is to have it different than `highlight` or `region` in order to be able to see the selected text. Before it was the same color which is very confusing.

**Comment by nashamri** [comment]
@syl20bnr Thanks for the feedback :smile: 
@duianto Okay I did a little change, I hope it's better now. Let me know what you think :smile:

**Comment by duianto** [comment]
It's a lot better thanks 😄

![lazy highlight dark theme](https://cloud.githubusercontent.com/assets/13420573/18397672/8c1fe21c-76c9-11e6-8fe8-589889b133c1.png)
![lazy highlight light theme](https://cloud.githubusercontent.com/assets/13420573/18397671/8c1c5cdc-76c9-11e6-93ca-4ada469d87c2.png)

**Comment by nashamri** [comment]
Okay great :smile: closing this one then.
