### ISSUE TITLE
[Help Needed] Changing Font Size In Agenda View

### ISSUE THREAD

**Issue by shan199105** [nashamri/spacemacs-theme#62]
Here is a screenshot of what agenda view looks like under spacemacs-black theme

<img width="291" alt="42bf282762bb9c9d97bb8d16deca040bae8fa01b_1_582x500" src="https://cloud.githubusercontent.com/assets/2152195/19616642/ac809bda-97e6-11e6-8352-241c1ffcba3e.png">

Is it possible for me to customize it to make it a smaller font size? 

Also when it is today, it seems the font for displaying today's tasks is even larger. I want it to be the same size as well.

I have searched the web and try to see how to customize these face settings but all failed. Really hope that I can get some help here. Thank you so much for the time.

**Comment by nashamri** [comment]
Hello @shan199105 thanks for reporting this.

I've introduced a new custom variable called `spacemacs-theme-org-agenda-height`. Just add:
```
(setq spacemacs-theme-org-agenda-height nil)
```
to your emacs config.

Just wait for MELPA to get the new updates :smile:

**Comment by shan199105** [comment]
Wow, that is awesome. Thank you so much for adding that variable, making things so much easier. Really appreciate your help here. 

Sorry for asking one more question here. Is it possible for me to make the task font size smaller for the org-agenda today view as well? I want to use the emacs default font size for that, it seems like the font size in agenda is larger than the emacs default font size.

Here is a screen shot:
![image](https://cloud.githubusercontent.com/assets/2152195/19621512/70cb5910-9861-11e6-86fe-e5fc9d650a48.png)

The upper green text is from agenda view, the lower text is the default font size.

Really sorry for bothering you again and again and thank you very much for the time.

**Comment by nashamri** [comment]
You are not bothering me at all :smile: 

The actual face names are:
1- for the "done" agenda entries is `org-agenda-done`
2- for the "todo" agenda entries is `org-scheduled`

Is the issue that you mentioned, only happening for the "DONE" entries?
or for all entries in org agenda?

Also, can you also post your font configurations (Your `dotspacemacs-default-font` variable value, if you are using spacemacs).

**Comment by shan199105** [comment]
![image](https://cloud.githubusercontent.com/assets/2152195/19621619/9a7b53b2-9863-11e6-9db5-7b74970eb127.png)

Here is the configuation for the `dotspacemacs-default-font` variable. I am using spacemacs, and I think I didn't have any customize setting on font, so that should be the default setting. 

<img width="1438" alt="pasted_image_2016-10-22__2_28_pm" src="https://cloud.githubusercontent.com/assets/2152195/19621635/f07bd692-9863-11e6-90bc-70443d5751bd.png">


Here is a fullscreen screenshot. I feel that the text in the right agenda view is bigger than the normal text font. It happens in all entries in org agenda.

**Comment by nashamri** [comment]
Hmmm..
I agree with you, it seems a little bit bigger. I'm not sure why, though.

On my end it looks like this:
![screenshot_20161022_193746](https://cloud.githubusercontent.com/assets/1207107/19621685/16059be8-988f-11e6-8681-ffb0778d50ab.png)

What I did is just put that custom variable in my `user-init` like so:
```
(defun dotspacemacs/user-init ()
  (setq spacemacs-theme-org-agenda-height nil))
```

And this is my font settings:
```
   dotspacemacs-default-font '("DejaVu Sans Mono" :size 13 :weight demibold :width normal :powerline-scale 1.1)
```

**Comment by nashamri** [comment]
Just tested the {day, week, year} view and it looks fine on my end.

**Comment by shan199105** [comment]
Hi, I went for a lunch outside. 

So the default behavior is to have the same font size? This is strange. 

I switched font to `DejaVu Sans Mono`. Below is a screenshot. It is perfect.
<img width="1440" alt="pasted_image_2016-10-22__4_27_pm" src="https://cloud.githubusercontent.com/assets/2152195/19622288/78d57db2-9874-11e6-91b5-3979a110d392.png">

So the problem is when I use the default font `Source Code Pro`. I do have `Source Code Pro` on my mac. Have no idea why it happened.  (I am using Mac Emacs with spacemacs)

![image](https://cloud.githubusercontent.com/assets/2152195/19622303/d35a652c-9874-11e6-8f97-e8815c07b9fc.png)

Mac Emacs Version: 25.1.1
Spacemacs Version: .200.2

========== Update ===========

Oh, it is a problem here. I found a warning in the message buffer that I don't have `DejaVu Sans Mono` installed on my mac, so I went to download that font. So now I do have that font installed. Then again, I opened the agenda and the problem reoccured. Here is a screenshot, using `DejaVu Sans Mono` font and with the font installed on my mac.

<img width="1440" alt="pasted_image_2016-10-22__4_38_pm" src="https://cloud.githubusercontent.com/assets/2152195/19622370/5d424286-9876-11e6-881d-28fc2c97f4ae.png">

Any idea why?

It seems that as long as I have the font installed, it will be slightly bigger. I think I will go ahead and delete all my config and try with the spacemacs default and see how it works.

**Comment by shan199105** [comment]
WoW, the default config seems to be good. It must be any of my config that mass this up. I will comment part of my config to see what caused this problem.

**Comment by shan199105** [comment]
Oh, even I remove the font from the mac the problem still exists. I thought the problem is gone is because without font, it is hard to find out that the font indeed a bit larger. It is just being more obvious when I install the font.

Sorry for the misleading. 

Here is a summary of the result I found.


First I am using the default config, so this is the process I am followed. 

1. remove the .spacemacs.d folder and reopen emacs to load default config
2. uncomment the org layer from the layer list
3. adding ~(setq spacemacs-theme-org-agenda-height nil)~ under user-config()
4. relaunch emacs, wait for it to load the org layer
5. create an org file.

```

* Inbox
** DONE test testestestestestse tes tse t set s et 1
   SCHEDULED: <2016-10-20 Thu>
** TODO testes tse t est es tes t  s ts etest se t s2
   SCHEDULED: <2016-10-21 Fri>
** TODO tes tes t est se tes t s ets et se t s etse t s 3
   SCHEDULED: <2016-10-22 Sat>
** DONE test s t set est se t set s ets et set  set st  t4
   SCHEDULED: <2016-10-21 Fri>

```

6. above is the org file I created, first task is done this Thursday. Second task is scheduled yesterday (Friday), not done yet. Third task is scheduled today, last task is scheduled yesterday but done. 

I can see the result is all the done tasks are larger. The task scheduled today is larger. As I mentioned before here is the pattern I found.

1. when any tasks scheduled for TODAY, they are larger even I have spacemacs-theme-org-agenda-height nil.
2. when I have any tasks done no matter in the past or not, they are larger.

**Comment by shan199105** [comment]
I have changed all the done item scale height to 1.0 it was 1.1 by default. So I guess, the done item is larger is a default behavior. Thank you so much for introducing me to the ~org-agenda-done~ face-type. That really helpful. 

This is the code I use to make the done tasks the same font size compare to others
````
(custom-set-faces
 '(org-agenda-done ((t (:foreground "#86dc2f" :height 1.0)))))
````

Now there is still one more problem here. The scheduled item for today is still larger even after I set the ~(setq spacemacs-theme-org-agenda-height nil)~, it seems that the ~org-scheduled~ face is for all the scheduled tasks. But right now, only the today's scheduled tasks are larger. 

Thank you very much for the help.

**Comment by shan199105** [comment]
In order to make today's scheduled task having the same font I find a face-type called ~org-scheduled-today~

so the following code can set the today's schedule height 1.0, default seems to be 1.3

````
(custom-set-faces
 '(org-scheduled-today ((t (:foreground "#bc6ec5" :height 1.0)))))
````

Now, everything in my agenda is having the same font size. Thank you very much for helping me. Without you help I will never know how to do it. Really appreciate.

**Comment by shan199105** [comment]
<img width="1431" alt="pasted_image_2016-10-22__8_52_pm" src="https://cloud.githubusercontent.com/assets/2152195/19623498/a4dc6e3c-9899-11e6-929b-8bf4de2c0b2f.png">

Here is a final screenshot. To summarize: below is config I use to make everything the same height(font size)

````
(custom-set-faces
 '(org-agenda-done ((t (:foreground "#86dc2f" :height 1.0)))))

(custom-set-faces
 '(org-scheduled-today ((t (:foreground "#bc6ec5" :height 1.0)))))
````

Finally, give 100 thumb up to the repo owner, love the spacemacs-theme.

**Comment by nashamri** [comment]
Hey @shan199105 thanks for investigating this. I actually missed the `org-scheduled-today` face :smile: now I pushed a new commit https://github.com/nashamri/spacemacs-theme/commit/db781c348b2ecdf871445986ef1cb2783c867ea0 to control this face (which might be the cause of the issues you were having) with the `spacemacs-theme-org-agenda-height` variable.

So, you might not need to include this:
```
(custom-set-faces
 '(org-scheduled-today ((t (:foreground "#bc6ec5" :height 1.0)))))
```
Anymore.

Thanks again :+1:

**Comment by shan199105** [comment]
That's great. I have removed that and it now works. Thanks for giving me hints at the first place. Very helpful. 😄

**Comment by dariushazimi** [comment]
Can u share the font setting you have. Looks really good.

**Comment by nuynait** [comment]
@dariushazimi Sure. Sorry for the late reply. This is the face customization I made to for my agenda.

This is the format customization
```
      (setq org-agenda-time-grid
            '((daily today today)
              #("----------------" 0 16 (org-heading t))
              (800 1000 1200 1400 1600 1800 2000 2200 2359))) ;; show default time lines
      (setq org-agenda-prefix-format '((agenda  . "%-10:T% s%?-2t") ; (agenda . " %s %-12t ")
                                       (timeline . "%-9:T%?-2t% s")
                                       (todo . "%i%-8:T")
                                       (tags . "%i%-8:T")
                                       (search . "%i%-8:T")))
      (setq org-agenda-remove-tags t)
```


This is the face Customization
```
      (custom-set-faces
       '(org-agenda-done ((t (:foreground "#86dc2f" :height 1.0)))))

      (custom-set-faces
       '(org-scheduled-today ((t (:foreground "DodgerBlue2" :height 1.0)))))
```

**I wrote a [blog post](http://blog.hourglasslab.com/2016/10/19/how%20do%20i%20organize%20my%20tasks%20and%20notes/) about how I config my emacs to manage tasks and store notes. Above config is also included with details.**

**Comment by ssfrr** [comment]
This still seems like an issue. I tried `(setq spacemacs-theme-org-agenda-height nil)` and still got varying font sizes in the agenda view. adding
```
  (custom-set-faces
   '(org-agenda-done ((t (:foreground "#86dc2f" :height 1.0)))))

  (custom-set-faces
   '(org-scheduled-today ((t (:foreground "#bc6ec5" :height 1.0)))))
```

as @nuynait suggested worked for me.

This is with spacemacs 0.200.13

**Comment by galexy** [comment]
I was able to get the variable to work. It needs to be set in (defun dotspacemcs/init() ...

**Comment by galexy** [comment]
The variable needs to be set in dotspacemcs/init(). The variable needs to be set before the package is loaded.
