### ISSUE TITLE
Make theme available for different programs

### ISSUE THREAD

**Issue by lpil** [nashamri/spacemacs-theme#64]
Hello!

I'm *really* enjoying this theme, and I've love to be able to use it with the Gnome terminal and other applications. Do these config files already exist? And if not would they be welcome contributions to this repo?

**Comment by nashamri** [comment]
Hello @lpil, :smile: 

Yes I believe this repo has what you are looking for: https://github.com/auduchinok/base16-builder
And you probably want to check this https://github.com/nashamri/spacemacs-theme/issues/29

**Comment by lpil** [comment]
Wonderful, thank you :)

**Comment by nashamri** [comment]
I probably need to update the README file to show this. So, I'm going to leave this issue open until I get that done.

**Comment by nashamri** [comment]
Okay, this is done. https://github.com/nashamri/spacemacs-theme#like-the-theme-and-want-to-use-it-in-other-places
