### ISSUE TITLE
Title-size in markdown files

### ISSUE THREAD

**Issue by fredefox** [nashamri/spacemacs-theme#70]
I wanted all text to have the same size, so I messed around with some config files and I didn't understand why my changes weren't being persisted until I tracked down that font-size scaling for headers in mardkown-files use hard-coded values. The issue is here:

[`spacemacs-common.el:527`](https://github.com/nashamri/spacemacs-theme/blob/master/spacemacs-common.el#L527)

Should be easy to fix my I'm a total emacs noob so I can't help

**Comment by ninrod** [comment]
just set this:   `(setq spacemacs-theme-org-height nil)`

**Comment by nashamri** [comment]
As @ninrod said, and you can check all the configurable variable here https://github.com/nashamri/spacemacs-theme#customizations

You can also do this via `customize` as in this short gif :smile: 
![peek 2017-02-08 23-09](https://cloud.githubusercontent.com/assets/1207107/22761761/16c9c25a-ee54-11e6-986e-f68eca40a0db.gif)

**Comment by fredefox** [comment]
That's very helpful. Thank you very much! I'll do it the spacemacs-way rather than hacking the theme-file.
