### ISSUE TITLE
Slightly different background colours for code and comments 

### ISSUE THREAD

**Issue by triklsbg** [nashamri/spacemacs-theme#71]
in my eyes irritating. Where does this come from? How can i avoid it?
Perhaps it is intentional?
![spc_light_screenshot_20170214_111935](https://cloud.githubusercontent.com/assets/3647083/22925851/8617e006-f2aa-11e6-8835-afb8ea7a83ff.png)
![spc_dark_screenshot_20170214_111736](https://cloud.githubusercontent.com/assets/3647083/22925857/8cd5bdb4-f2aa-11e6-976b-c576110e8c5b.png)

**Comment by ninrod** [comment]
see [here](https://github.com/nashamri/spacemacs-theme#customizations).

you want to set `spacemacs-theme-comment-bg` to nil, like this:

```elisp
(setq spacemacs-theme-comment-bg nil)
```

**Comment by nashamri** [comment]
@triklsbg As @ninrod said :smile: 
Thanks @ninrod :+1:

**Comment by triklsbg** [comment]
Thanks, i put it in the dotspacemacs/user-config definition.

**Comment by nashamri** [comment]
yeah that should do it :smile:
