### ISSUE TITLE
Default #b2b2b2 and Shadow #b3b3b3 foreground colors are almost identical

### ISSUE THREAD

**Issue by duianto** [nashamri/spacemacs-theme#72]
### Description
The foreground colors, default: `#b2b2b2` and shadow: `gray70` (`#b3b3b3`) are almost identical when the current theme is `spacemacs-dark`.

This was noticed in the `evil-ex` <kbd>S-;</kbd> prompt. Because it shows the previous command with the shadow foreground color. The almost identical colors makes it difficult to see a difference between a previous and a current command.

In the `spacemacs-light` theme, the shadow foreground color is `gray50` (`#7f7f7f`), that's a little bit dimmer than the default foreground color: `#655370`, but it could probably be changed so that the difference is more obvious.

The shadow color can be seen and changed here:
- Open the HELM Colors <kbd>SPC C l</kbd>
- Type: `shadow`
- Navigate down twice <kbd>C-j C-j</kbd> to the shadow entry under the "Custom Face" heading
- Press <kbd>RET</kbd>

### Question
I can't find a reference in the `spacemacs-theme` repository, to any of these colors: `gray70`, `b3b3b3`, `gray50`, or `7f7f7f`.

There's only one mention of "shadow", but it's for `dired-ignored`:
`(dired-ignored ((,class (:inherit shadow))))`. [1] (side note below)

In the Spacemacs repository, there's no mention of `b3b3b3` or `7f7f7f` (which are the `gray70` and `gray50` hex colors), and `gray50` and `gray70` are only used in a couple of `nyan-*.xpm` files. 

When the default Spacemacs theme `spacemacs-dark` is changed to `spacemacs-light` <kbd>SPC T n</kbd>, then the shadow color changes from `gray70` to `gray50`. That made me think that maybe it is changed by the spacemacs-themes after all.

Should this be handled by the spacemacs-theme or the Spacemacs repository?

### Possible solution
I noticed that in `spacemacs-common.el` there's a `base-dim` variable:
```
  (dyn-let ((class '((class color) (min-colors 89))) ;;              ~~ Dark ~~                              ~~ Light ~~
        ;;                                                          GUI       TER                           GUI       TER
...
        (base-dim      (if (eq variant 'dark) (if (true-color-p) "#686868" "#585858") (if (true-color-p) "#a094a2" "#afafd7")))
```

The "GUI" colors `#686868` (for the dark theme) and `#a094a2` (for the light theme) seem to be much better colors for telling the difference between dimmed and default text.

Here's two images showing the different text colors:

![color examples](https://cloud.githubusercontent.com/assets/13420573/23064886/eb8c2cc0-f512-11e6-88ed-73defd178478.png)
![color examples light](https://cloud.githubusercontent.com/assets/13420573/23064889/ee909c44-f512-11e6-85bd-83b9489a394a.png)

If the spacemacs-theme is going to handle this, then this might be useful. 
The `evil-ex-previous-command` seems to be assigned here:
`.emacs.d/elpa/evil-20170215.1319/evil-ex.el#L189`
``` elisp
                      (propertize evil-ex-previous-command 'face 'shadow)))
```

[1] Side note: 
Maybe `dired-ignored` should use the `base-dim` color instead of `'shadow` so that it's color will be controlled by the spacemacs-theme. Otherwise there's a risk that dimmed text will look incorrect if the shadow foreground color has been changed outside the spacemacs-themes)

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 3072e727)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((markdown :variables markdown-live-preview-engine 'vmd)
 auto-completion chrome emacs-lisp git helm html markdown org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by nashamri** [comment]
Yeah there's no theming for the face `shadow` which other modes inherit from. I think this could be solved by assigning `base-dim` to  the `shadow` face, as you suggested. I'll fix this now :smile:

**Comment by nashamri** [comment]
Wait for MELPA to update, and please close this issue if you think it's fixed.

**Comment by duianto** [comment]
It's taking a while for MELPA to update. This repository was updated 7 hours ago. I'm just guessing but maybe there's a delay before it looks for an update from a recently updated repository.

I'm sure it works, so I'll close this now. Thanks for fixing this.
