### ISSUE TITLE
Diff-file-header is hard to read in the spacemacs-dark theme

### ISSUE THREAD

**Issue by duianto** [nashamri/spacemacs-theme#74]
### Description
With the `spacemacs-dark` theme enabled, and a `*Diff*` buffer open. Then the `diff-file-header`'s background color (`gray60`) makes it hard to read the file paths:

![diff-file-header_hard-to-read](https://cloud.githubusercontent.com/assets/13420573/23338476/9f9a6b00-fc0c-11e6-9829-c3adb261b576.png)

In the `spacemacs-light` theme it's easy to read the `diff-file-header` text, so it can probably be left as it is.

### Steps to open a `*Diff*` buffer:

1. Press: <kbd>SPC a d</kbd>
2. Navigate to a directory with two files and press <kbd>RET</kbd>
3. In the `Dired by name` buffer, move the cursor on one file and press <kbd>=</kbd>
4. Choose another file and press <kbd>RET</kbd>

PS. <kbd>M-x</kbd> `diff`, and picking two files is probably a quicker way to open a Diff buffer.

### Face attributes
With the cursor on the hard to read text, 

- Open the `Eval:` prompt: <kbd>S-M-;</kbd>
- Type: `(text-properties-at (point))`
- The minibuffer shows: `(face (diff-file-header diff-header) fontified t)`

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 0c8af968)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey helm auto-completion emacs-lisp git)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by nashamri** [comment]
All done :+1: thanks @duianto for finding this :smile:
