### ISSUE TITLE
org header size

### ISSUE THREAD

**Issue by gregf** [nashamri/spacemacs-theme#76]
Is there a way to adjust the font size for org-mode headers? I know theres the setting to enable/disable varying size, but the font is larger than I would like at the top level heading.

**Comment by ninrod** [comment]
see #70

**Comment by gregf** [comment]
This isn't what I want. That just makes it so all the headers are the same size. My problem is they are to big. I want to make them smaller.

**Comment by nashamri** [comment]
@gregf I think you can do something like this in your `user-config`, if you are using spacemacs:
```elisp
(add-hook 'org-mode-hook (lambda ()
          (set-face-attribute 'org-level-1 nil :height 0.8)))
```
Just choose the height you like. The example above will work for org-mode only, so if you want it for other modes, you have to add the appropriate hook.

The org header faces are named `org-level-1, org-level-21, etc...

**Comment by gregf** [comment]
That did it, thank you!
