### ISSUE TITLE
Green diff overlays, make blue text almost invisible

### ISSUE THREAD

**Issue by duianto** [nashamri/spacemacs-theme#79]
When a file with a merge conflict is opened, then it shows red and green colored diff sections. 

Blue comment/keyword text becomes almost invisible in the bright green sections. 
And green text in the bright red sections, makes the text almost "vibrate".

![blue and cyan text almost invisible under green overlay](https://user-images.githubusercontent.com/13420573/27042103-4b5b553a-4f96-11e7-87f0-a63b95b4467e.png)

This is what the text looks like without the green diff overlay:

![without green diff colors](https://user-images.githubusercontent.com/13420573/27042129-5fbf0b52-4f96-11e7-8bb3-70b6efac7541.png)

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 377cb2f4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion colors emacs-lisp git helm markdown org ranger
            (spell-checking :variables spell-checking-enable-by-default nil)
            syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by nashamri** [comment]
Thanks @duianto I think I fixed it:
![smerge](https://user-images.githubusercontent.com/1207107/27132776-fd6b6df6-5107-11e7-9d2c-480978bcdd17.png)

![smerge-light](https://user-images.githubusercontent.com/1207107/27132783-026841a8-5108-11e7-9490-89c43b767c07.png)

**Comment by nashamri** [comment]
Oh and another thing, now spacemacs has its own copy of the theme. So, until these new changes get commited to spacemacs codebase, you can get these updates from MELPA.

**Comment by duianto** [comment]
That looks great (as usual), thanks 👍 

Yeah I know about Spacemacs using a local copy. The reason seems to be, so that the theme is available earlier in the startup process, and to improve reliability if there are any startup or package install issues.

Source: spacemacs-theme updates available, but I'm getting "All packages are up to date" [#8397](https://github.com/syl20bnr/spacemacs/issues/8397#issuecomment-283119721)

It looks like the local spacemacs-theme is being tracked on the Spacemacs repository as well. If it's not a lot of extra work for you, then maybe you could make a PR when there's an update. I'm sure you want Spacemacs to use the latest version. TheBB is actively merging PRs so it might get merged quickly.

I'm not in a hurry, to get this feature implemented (because i don't make merge conflicts 😜😆), but someone else might also find this useful.

If your busy, then it might be better to ping the Spacemacs team, to merge all changes since the last update, possibly once a week/month, or if there's a major update.

I'm not sure how to use the MELPA version at the same time as the local version. The link above shows some issues I ran into while trying to install the MELPA version.

**Comment by nashamri** [comment]
I was actually looking at the last commit merged with spacemacs to prepare a PR :smile:
I'll send one right now and hopefully a new version of spacemacs will be released soon :beers:

**Comment by duianto** [comment]
I got a merge conflict that shows the `smerge-refined-changed` face:

![merge conflict](https://user-images.githubusercontent.com/13420573/27276957-098566d6-54dd-11e7-8b2e-777c57cafc78.png)

### Problem:
It isn't obvious that the merge conflicts changed (blue) text, isn't just part
of the regular text, since it looks so similar to the function and keyword text
above the merge conflict.

### Possible cause:
I noticed that two of the spacemacs-theme colors are almost identical:
`green-bg` `#293235` which is used by `smerge-other`, and
`blue-bg` `#293239` which is used by `smerge-refined-changed`.

And the `smerge-refined-{added,removed}` faces, use colors with `-s` at the end:
`green-bg-s` `#29422d` and `red-bg-s` `#512e31`, but `smerge-refined-changed`
uses the color `blue-bg`:
``` elisp
`(smerge-refined-added ((,class (:background ,green-bg-s :foreground ,green))))
`(smerge-refined-changed ((,class (:background ,blue-bg :foreground ,blue))))
`(smerge-refined-removed ((,class (:background ,red-bg-s :foreground ,red))))
```

### Possible solution:
`spacemacs-common.el` doesn't have a definition for a `blue-bg-s` color. If it
was added as a brighter blue, then it could be used as the
`smerge-refined-changed` background.

That would probably make it more obvious that the blue text in the merge
conflict is different from the regular function/keyword text.

### Additional notes:
The hue for the `green-bg` (138) and `blue-bg` (146) should probably be
separated more.

The `;; colors` section in `spacemacs-common.el` should probably be sorted
alphabetically.
The non-alphabetically ordered colors are:
- cyan
- blue
- blue-bg
- magenta

**Comment by nashamri** [comment]
Yup! good notes. Will fix that :smile:

**Comment by nashamri** [comment]
Added a new color `blue-bg-s` that should solve this issue.

Thanks @duianto :+1:
