### ISSUE TITLE
Option to enable italics for comments

### ISSUE THREAD

**Issue by rafaelrinaldi** [nashamri/spacemacs-theme#82]
First of all thanks for the theme, I like it a lot.

One thing I miss a lot is comments in italics. I noticed you already have an option to toggle the background color for them and was wondering if there's interest on implementing an option to toggle italics too?

**Comment by nashamri** [comment]
Thank you @rafaelrinaldi 😄 
Yeah I think this is a good idea and can be easily implemented. Will do!

**Comment by rafaelrinaldi** [comment]
@nashamri I can give it a shot if you would like.

**Comment by nashamri** [comment]
Yeah sure, shoot me a pull request and we'll take it from there 👍

**Comment by ninrod** [comment]
yeah, itallics for comments work well. I did __[this](https://github.com/ninrod/spacemacs-theme/commit/9e80dca160e085f4bda8602530887178de5d69d8)__ with my personal fork of spacemacs theme.

**Comment by nashamri** [comment]
Yes @ninrod, the change is pretty simple. Additonally, I would prefer to have a variable to control this and make it off by default. So something like this:

```lisp
(defcustom spacemacs-theme-comment-italic nil
  "Make the comment lines italic."
  :type 'boolean
:group 'spacemacs-theme)
```

And then something like this:
```lisp
     `(font-lock-comment-face ((,class (
              :slant (when spacemacs-theme-comment-italic italic)
              :foreground ,subdued-comment
              :background ,(when spacemacs-theme-comment-bg comment-bg)))))
```

I did not test this, so if @rafaelrinaldi can try that and send a PR, that would be great 😄

**Comment by nashamri** [comment]
Fixed in https://github.com/nashamri/spacemacs-theme/commit/11d6958364271e11c920015c24d509f9bdcce6c9

**Comment by harveyslash** [comment]
very new to spacemacs. can you tell me where to put this option to enable italics in comments ?

**Comment by rafaelrinaldi** [comment]
@harveyslash You can press <kbd>⌘</kbd>+<kbd>,</kbd>. You'll get to the settings panel, then you just search for `spacemacs-theme-comment-italic` on the search field.

**Comment by williamJmelton** [comment]
I am still unsure how to make the comments italic. I have placed @nashamri code in my init file but does nothing - I have also tried @rafaelrinaldi suggestion and cannot find spacemacs-theme-comment-italic in the settings page when searching.

**Comment by rafaelrinaldi** [comment]
It looks like this got removed from the theme options?
