### ISSUE TITLE
type face and func face look almost the same

### ISSUE THREAD

**Issue by bmag** [nashamri/spacemacs-theme#9]
Using dark GUI variant, functions and types look almost the same:
![spacemacs-dark-before-springgren3](https://cloud.githubusercontent.com/assets/4334375/8634584/d848c23e-2806-11e5-939f-6802271f5a42.png)

I changed locally so that `font-lock-type-face` uses "SpringGreen3", and IMO it looks better:
![spacemacs-dark-with-springgreen3](https://cloud.githubusercontent.com/assets/4334375/8634589/0d688832-2807-11e5-952e-ab16a4e3cdd2.png)

Haven't tried the other variants, may suffer the same problem.

**Comment by nashamri** [comment]
Thanks for reporting this @bmag :+1: got it fixed for both variants.
