### ISSUE TITLE
Show-paren-mode erroneously highlights the left margin

### ISSUE THREAD

**Issue by seagle0128** [nashamri/spacemacs-theme#91]
Please refer to the similar issue on https://github.com/oneKelvinSmith/monokai-emacs/pull/83 and https://lists.gnu.org/archive/html/bug-gnu-emacs/2015-10/msg01050.html.

The workaround is
```elisp
(custom-set-faces '(linum ((t (:inherit default)))))
```

**Comment by nashamri** [comment]
@seagle0128 Thanks for this, will update the theme now.
