### ISSUE TITLE
Unable to tweak theme

### ISSUE THREAD

**Issue by mssdvd** [nashamri/spacemacs-theme#92]
I customized 'spacemacs-theme-comment-bg' and 'spacemacs-theme-comment-italic' but nothing is changed. Iosevka font supports italic fonts.

![image](https://user-images.githubusercontent.com/18464329/31866523-1ef7d312-b781-11e7-8e77-9e1ea3e58f7a.png)

Config file:
https://hastebin.com/rofayutequ.sql

**Comment by nashamri** [comment]
hello @mssdvd,

I just checked your config file, I believe you didn't actually install the theme. Add this to your packages
`(use-package spacemacs-theme)`

**Comment by mssdvd** [comment]
Strange. I reinstalled the package with 'package-reinstall' and the comments were italic but when I create a new client frame or I launch a new instance of emacs, it doesn't work well.

**Comment by nashamri** [comment]
Here are the steps I did and it was working for me:

1. Copied your config file and rename it to `init.el` in the `.emacs.d` dir.
2. Added `(use-package spacemacs-theme)` around line 200, in your packages.
3. Stared emacs and `M-x load-theme` and picked `spacemacs-dark`.

Also, this might help https://github.com/nashamri/spacemacs-theme/issues/42

**Comment by mssdvd** [comment]
It works! Thank you!

**Comment by nashamri** [comment]
😄 glad it did, and thanks for the ⭐️
