### ISSUE TITLE
Spacemacs Light Theme - Odd markdown pre colors

### ISSUE THREAD

**Issue by deybhayden** [nashamri/spacemacs-theme#93]
<img width="747" alt="screen shot 2017-11-13 at 9 42 44 pm" src="https://user-images.githubusercontent.com/877908/32761893-a9dedf20-c8bb-11e7-8d63-6ad1b6fe4f88.png">

Wasn't sure if this was intentional or not, but 3 backtick sections look pretty jarring?

**Comment by nashamri** [comment]
Hey @deybhayden no it's not intentional :smile:
Are you using spacemacs or emacs? and do you mind sharing how you load the theme? It seems like a loading issue to me.

**Comment by deybhayden** [comment]
Oh, you know what, it has to do with "cycling" my themes. I default to dark mode, but use light on occasion. If I do light on launch, I don't have that issue.

**Comment by nashamri** [comment]
Yeah that makes sense. This PR https://github.com/nashamri/spacemacs-theme/pull/89 might solve it. Having two variants of the theme caused some issues when loading/switching between the two variants.

**Comment by nashamri** [comment]
@deybhayden glad you figured it out! thanks for closing this.
