### ISSUE TITLE
company-mode common part highlight is not clear

### ISSUE THREAD

**Issue by stardiviner** [nashamri/spacemacs-theme#96]
![spacemacs-theme company-mode common part](https://user-images.githubusercontent.com/378699/33589026-1bde6b1c-d9b1-11e7-8174-30d560206dd2.png)
As the screenshot displays, the common part `company-tooltip-common` is not very clear. It is almost same color with the background color.
![spacemacs 2](https://user-images.githubusercontent.com/378699/33589121-ae8db06c-d9b1-11e7-8307-f1f641a729e3.png)

**Comment by nashamri** [comment]
@stardiviner thanks :+1: pushed a fix for this.
