### ISSUE TITLE
ace-window leading char face is very small

### ISSUE THREAD

**Issue by stardiviner** [nashamri/spacemacs-theme#98]
```elisp
(set-face-attribute 'aw-leading-char-face nil
                      :height 2.5 :weight 'bold)
```
I hope by default `spacemacs-theme` will set `ace-window` leading char face larger.

**Comment by nashamri** [comment]
Yeah that sounds like a good idea @stardiviner

**Comment by nashamri** [comment]
Made it double the size, 2.5 seemed too big :smile: 
Thanks @stardiviner

**Comment by eflanigan00** [comment]
Is there a way to prevent the screen from resizing when this is evoked?

**Comment by nashamri** [comment]
@eflanigan00 I'm not sure what you mean? maybe a screenshot would help?
